# createParameterDescriptionsDF.r
#
# Returns a dataframe with initial parameter descriptions, as used by the EPA
# as of 24-Oct-2010.
#
# 10/24/2010 cws created
#
  
createParameterDescriptionsDF <- function() 
#
{
  rc <-
  structure(list(
    FORMABBR = c("VAssess", "VAssess", "VAssess",
        "VAssess", "VAssess", "VAssess", "VAssess", "VAssess", "VAssess",
        "VAssess", "VAssess", "VAssess", "VAssess", "VAssess", "VAssess",
        "VAssess", "VAssess", "VAssess", "VAssess", "VAssess", "VAssess",
        "VAssess", "VAssess", "VAssess", "VAssess", "VAssess", "VAssess",
        "VAssess", "VAssess", "VAssess", "VAssess", "VAssess", "VAssess",
        "VAssess", "VAssess", "VAssess", "VAssess", "VAssess", "VAssess",
        "VAssess", "VAssess", "VAssess", "VAssess", "VAssess", "VAssess",
        "SampColB", "SampColB", "SampColB", "SampColB", "SampColB", "SampColB",
        "SampColB", "SampColB", "SampColW", "SampColW", "SampColW", "SampColW",
        "SampColW", "SampColW", "SampColW", "SampColW", "SampColW", "SampColW",
        "SampColW", "SampColW", "FieldMB", "FieldMB", "FieldMB", "FieldMB",
        "FieldMB", "FieldMB", "FieldMB", "FieldMB", "FieldMB", "FieldMB",
        "FieldMB", "FieldMB", "FieldMB", "FieldMB", "FieldMB", "FieldMB",
        "FieldMB", "FieldMB", "FieldMB", "FieldMB", "FieldMB", "FieldMB",
        "FieldMB", "FieldMB", "FieldMB", "FieldMB", "FieldMW", "FieldMW",
        "FieldMW", "FieldMW", "FieldMW", "FieldMW", "FieldMW", "FieldMW",
        "FieldMW", "FieldMW", "FieldMW", "FieldMW", "FieldMW", "FieldMW",
        "FieldMW", "FieldMW", "FieldMW", "FieldMW", "FieldMW", "FieldMW",
        "FieldMW", "FieldMW", "FieldMW", "FieldMW", "FieldMW", "FieldMW",
        "SampColB", "SampColB", "SampColW", "SampColW", "SampColB", "SampColB",
        "SampColB", "SampColB", "SampColB", "SampColB", "SampColB", "SampColB",
        "SampColB", "SampColB", "SampColB", "SampColW", "SampColW", "SampColW",
        "SampColW", "SampColW", "SampColW", "SampColW", "SampColW", "SampColW",
        "SampColW", "SampColW", "FieldMB", "FieldMB", "FieldMB", "FieldMB",
        "FieldMB", "FieldMB", "FieldMB", "FieldMB", "FieldMB", "FieldMB",
        "FieldMW", "FieldMW", "FieldMW", "FieldMW", "FieldMW", "FieldMW",
        "FieldMW", "FishB", "FishB", "FishB", "FishB", "FishB", "FishB",
        "FishB", "FishB", "FishB", "FishB", "FishB", "FishB", "FishB",
        "FishB", "FishB", "FishB", "FishB", "FishB", "FishB", "FishB",
        "FishB", "FishB", "FishW", "FishW", "FishW", "FishW", "FishW",
        "FishW", "FishW", "FishW", "FishW", "FishW", "FishW", "FishW",
        "FishW", "FishW", "FishW", "FishW", "FishW", "FishW", "FishW",
        "FishW", "FishW", "FishGear", "FishGear", "FishGear", "FishGear",
        "FishGear", "FishGear", "SD", "SD", "SD", "SD", "SD", "SD", "SD",
        "SD", "SD", "SD", "SD", "SD", "SD", "SD", "SD", "SD", "SD", "SD",
        "SD", "SD", "SD", "SD", "SD", "SD", "SD", "SD", "RipLegacy",
        "RipLegacy", "RipLegacy", "RipLegacy", "RipLegacy", "RipLegacy",
        "RipLegacy", "RipLegacy", "RipLegacy", "RipLegacy", "RipLegacy",
        "RipLegacy", "RipLegacy", "RipLegacy", "RipLegacy", "RipLegacy",
        "VAssess", "VAssess", "LM-SC", "LM-SC", "LM-SC", "", "", "",
        "", "", "SampColB", "SampColB", "SampColB", "SampColB", "SampColB",
        "SampColW", "SampColW", "SampColW", "SampColW", "SampColW", "SampColB",
        "SampColB", "SampColB", "SampColB", "SampColB", "SampColW", "SampColW",
        "SampColW", "SampColW", "SampColW", "SampColB", "SampColB", "SampColB",
        "SampColB", "SampColB", "SampColW", "SampColW", "SampColW", "SampColW",
        "SampColW", "SampColB", "SampColB", "SampColB", "SampColB", "SampColB",
        "SampColW", "SampColW", "SampColW", "SampColW", "SampColW", "ChRip",
        "ChRip", "ChRip", "ChRip", "ChRip", "ChRip", "ChRip", "ChRip",
        "ChRip", "ChRip", "ChRip", "ChRip", "ChRip", "ChRip", "ChRip",
        "ChRip", "ChRip", "ChRip", "ChRip", "ChRip", "ChRip", "ChRip",
        "ChRip", "ChRip", "ChRip", "ChRip", "ChRip", "ChRip", "ChRip",
        "ChRip", "ChRip", "ChRip", "ChRip", "ChRip", "ChRip", "ChRip",
        "ChRip", "ChRip", "ChRip", "ChRip", "ChRip", "ChRip", "ChRip",
        "ChRip", "ChRip", "ChRip", "ChRip", "ChRip", "ChRip", "ChRip",
        "ChRip", "ChRip", "ChRip", "ChRip", "ChRip", "ChRip", "ChRip",
        "ChRip", "ChRip", "ChRip", "ChRip", "ChRip", "ChRip", "ChRip",
        "ChRip", "ChRip", "ChRip", "ChRip", "ChRip", "ChRip", "ChRip",
        "ChRip", "ChRip", "ChRip", "ChRip", "ChRip", "ChRip", "ChRip",
        "ChRip", "ChRip", "ChRip", "ChRip", "ChRip", "ChRip", "ChRip",
        "ChRip", "ChRip", "ChRip", "ChRip", "ChRip", "ChRip", "ChRip",
        "ChRip", "ChRip", "ChRip", "ChRip", "ChRip", "ChRip", "ChRip",
        "ChRip", "ChRip", "ChRip", "ChRip", "ChRip", "ChRip", "ChRip",
        "ChRip", "ChRip", "ChRip", "ChRip", "ChRip", "ChRip", "ChRip",
        "ChRip", "ChRip", "ChRip", "ChRip", "ChRip", "ChRip", "ChRip",
        "ChRip", "ChRip", "ChRip", "ChRip", "ChRip", "ChRip", "ChRip",
        "ChRip", "ChRip", "ChRip", "ChRip", "ChRip", "ChRip", "ChRip",
        "ChRip", "ChRip", "ChRip", "ChRip", "ChRip", "ChRip", "ChRip",
        "ChRip", "ChRip", "ChRip", "ChRip", "ChRip", "ChRip", "ChRip",
        "ChRip", "ChRip", "ChRip", "ChRip", "ChRip", "ChRip", "ChRip",
        "ChRip", "ChRip", "ChRip", "ChRip", "ChRip", "ChRip", "ChRip",
        "ChRip", "ChRip", "ChRip", "ChRip", "ChRip", "CC", "CC", "CC",
        "CC", "CC", "CC", "CC", "Slope", "Slope", "Slope", "Slope", "Slope",
        "Slope", "Slope", "Slope", "Slope", "Slope", "Slope", "Slope",
        "Slope", "Thal", "Thal", "Thal", "Thal", "Thal", "Thal", "Thal",
        "Thal", "Thal", "Thal", "Thal", "Thal", "Thal", "Thal", "Thal",
        "Thal", "Thal", "Thal", "Thal", "Thal", "Thal", "Thal", "Thal",
        "Thal", "Thal", "Thal", "Thal", "Thal", "Thal", "Thal", "Thal",
        "Thal", "Thal", "Thal", "Thal", "Thal", "Thal", "Thal", "Thal",
        "Thal", "Thal", "Thal", "Thal", "Thal", "Thal", "LM-SC", "LM-SC",
        "LM-SC", "SampColB", "SampColB", "SampColW", "SampColW", "SampColB",
        "SampColB", "SampColB", "SampColB", "SampColW", "SampColW", "SampColW",
        "SampColW", "LM-SC", "LM-SC", "LM-SC", "LM-SC", "TorEv", "TorEv",
        "TorEv", "TorEv", "TorEv", "TorEv", "TorEv", "TorEv", "TorEv",
        "TorEv", "TorEv", "", "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "StrmVer", "StrmVer", "StrmVer", "StrmVer",
        "StrmVer", "StrmVer", "StrmVer", "StrmVer", "StrmVer", "StrmVer",
        "StrmVer", "StrmVer", "StrmVer", "StrmVer", "StrmVer", "StrmVer",
        "StrmVer", "StrmVer", "StrmVer", "StrmVer", "StrmVer", "StrmVer",
        "StrmVer", "StrmVer", "SampColB", "SampColB", "SampColB", "SampColW",
        "SampColW", "SampColW", "LM-SC", "LM-SC", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "FieldMB",
        "FieldMW", "Thal", "Thal")
   ,PARAMETER = c("AGR_CROP", "AGR_IRRG",
        "AGR_ORCH", "AGR_PAS", "AGR_POUL", "AGR_STCK", "AGR_WITH", "APPEALING",
        "BEAVER", "BVFLMOD", "DLANDUSE", "FORAGECL", "GEN_COM", "IND_COML",
        "IND_FIRE", "IND_IND", "IND_LOG", "IND_MINE", "IND_ODOR", "IND_OIL",
        "IND_POWR", "MAN_ANGL", "MAN_CHAN", "MAN_DAMS", "MAN_DRED", "MAN_DWT",
        "MAN_FISH", "MAN_LIME", "MAN_WLF", "PRISTINE", "REASON", "REC_FILM",
        "REC_PARK", "REC_PRIM", "REC_TRAS", "REC_TRLS", "RES_BRID", "RES_CON",
        "RES_DUMP", "RES_LAWN", "RES_PIPE", "RES_RES", "RES_ROAD", "RES_SEWG",
        "WEATHCOM", "CHANNEL", "HABITAT", "JAR_NO", "LOCATION", "PRESERVED",
        "SAMPLE_ID", "SECOND_HABITAT", "SUBSTRATE", "CHANNEL", "EDGE",
        "JAR_NO", "LOCATION", "PRESERVED", "SAMPLE_ID", "SUBSTRATE",
        "CHANNEL", "JAR_NO", "PRESERVED", "SAMPLE_ID", "SUBSTRATE", "CAL_INST_ID",
        "CAL_INST_MODEL", "CAL_INST_OPERATOR", "COND_QCS_DESC", "COND_QCS_MEASURED",
        "COND_QCS_TRUE", "COND_STD1_DESC", "COND_STD1_VALUE", "COND_STD2_DESC",
        "COND_STD2_VALUE", "DO_BARO_PRESSURE", "DO_CALIBRATION_VALUE",
        "DO_CALIBRATION_VALUE", "DO_DISPLAYED_VALUE", "DO_ELEVATION",
        "DO_ELEVATION", "DO_PRESSURE", "PH_QCS_DESC", "PH_QCS_MEASURED",
        "PH_QCS_TRUE", "PH_STD1_DESCRIPTION", "PH_STD1_VALUE", "PH_STD2_DESCRIPTION",
        "PH_STD2_VALUE", "TEMP_SENSOR", "TEMP_THERMOMETER", "CAL_INST_ID",
        "CAL_INST_MODEL", "CAL_INST_OPERATOR", "COND_QCS_DESC", "COND_QCS_MEASURED",
        "COND_QCS_TRUE", "COND_STD1_DESC", "COND_STD1_VALUE", "COND_STD2_DESC",
        "COND_STD2_VALUE", "DO_BARO_PRESSURE", "DO_CALIBRATION_VALUE",
        "DO_CALIBRATION_VALUE", "DO_DISPLAYED_VALUE", "DO_ELEVATION",
        "DO_ELEVATION", "DO_PRESSURE", "PH_QCS_DESC", "PH_QCS_MEASURED",
        "PH_QCS_TRUE", "PH_STD1_DESCRIPTION", "PH_STD1_VALUE", "PH_STD2_DESCRIPTION",
        "PH_STD2_VALUE", "TEMP_SENSOR", "TEMP_THERMOMETER", "CHILLED",
        "SAMPLE_ID", "CHILLED", "SAMPLE_ID", "DEPTH_COLLECTED", "FILTER_1",
        "FILTER_2", "FILTER_3", "FILTER_4", "FILTER_END_TIME", "FILTER_START_TIME",
        "SAMPLE_ID", "SAMPLE_VOL", "TIME_COLLECTED", "TIME_FROZEN", "DEPTH_COLLECTED",
        "FILTER_1", "FILTER_2", "FILTER_3", "FILTER_4", "FILTER_END_TIME",
        "FILTER_START_TIME", "SAMPLE_ID", "SAMPLE_VOL", "TIME_COLLECTED",
        "TIME_FROZEN", "BANK", "CLEAR_TO_BOTTOM", "CONDUCTIVITY", "CORRECTED",
        "DISAPPEARS", "DO", "pH", "REAPPEARS", "TEMPERATURE", "TIME",
        "BANK", "CONDUCTIVITY", "CORRECTED", "DO", "pH", "TEMPERATURE",
        "TIME", "ACTUAL_DATE", "ANOM_CT", "BANK", "BANK_OTHER", "COUNT",
        "COVER", "COVER_OTHER", "DEPTH", "DIST_SAMPLED", "FINAL_CT",
        "MORT_CT", "NAME_COM", "NO_FISH", "PHOTO", "PHOTO_FILE", "SHOCK_TIME",
        "SUB_OTHER", "SUBSTRATE", "TAG", "TL_MAX", "TL_MIN", "VOUCH_CT",
        "ACTUAL_DATE", "ANOM_CT", "COUNT", "FINAL_CT", "MORT_CT", "NAME_COM",
        "PHOTO", "TAG", "TL_MAX", "TL_MIN", "TRANA", "TRANB", "TRANC",
        "TRAND", "TRANE", "TRANF", "TRANG", "TRANH", "TRANI", "TRANJ",
        "VOUCH_CT", "COMMON_NAME", "FROZEN", "PRESERVED", "SAMPLE_ID",
        "SUBREACH", "TTL_LENGTH", "AVGWIDTH", "AVGWIDTH", "DEPTH", "DEPTH",
        "DEPTH_1", "DEPTH_2", "DEPTH_3", "DEPTH_4", "DEPTH_5", "DEPTH_1",
        "DEPTH_2", "DEPTH_3", "DEPTH_4", "DEPTH_5", "DISTBANK", "DISTBANK",
        "FLOAT", "FLOAT", "METHOD", "QVAL", "QVAL", "TIME", "TOTTIME",
        "VELOCITY", "VELOCITY", "VOLUME", "DBH", "E_WTRMILF", "FLWR_RUSH",
        "G_REED", "HEIGHT", "HYDRILLA", "MF_ROSE", "NO_INVASIVES", "NOT_VIS",
        "P_LSTRIFE", "SALT_CED", "SPECIES", "SPURGE", "TREE_TYP", "W_HYACINTH",
        "YLW_FLHEAR", "CONFIDENCE", "PREVALANCE", "JAR_NO", "SAMPLE_ID",
        "TYPE", "ANALYTE", "HOLDING_TIME", "HOLDING_TIME_ALERT", "HOLDING_TIME_UNITS",
        "REPORTING_LIMIT_ALERT", "COMP_VOL", "FROZEN", "SAMPLE_ID", "TRANNO",
        "VOLUME", "COMP_VOL", "FROZEN", "SAMPLE_ID", "TRANNO", "VOLUME",
        "COMP_VOL", "FROZEN", "SAMPLE_ID", "TRANNO", "VOLUME", "COMP_VOL",
        "FROZEN", "SAMPLE_ID", "TRANNO", "VOLUME", "COMP_VOL", "FROZEN",
        "SAMPLE_ID", "TRANNO", "VOLUME", "COMP_VOL", "FROZEN", "SAMPLE_ID",
        "TRANNO", "VOLUME", "COMP_VOL", "PRESERVED", "SAMPLE_ID", "TRANNO",
        "VOLUME", "COMP_VOL", "PRESERVED", "SAMPLE_ID", "TRANNO", "VOLUME",
        "ALGAE", "ANGLE", "BARE", "BOULDR", "BRUSH", "BUILD", "CANBTRE",
        "CANSTRE", "CANVEG", "CONSTRT", "DENSIOM", "GCNWDY", "GCWDY",
        "LANDFL", "LOG", "LVTREE", "MACPHY", "MINE", "PARK", "PAST",
        "PAVE", "PIPES", "ROAD", "ROW", "SEEOVRBK", "SHOR2RIP", "STRUCT",
        "UNDCUT", "UNDERCUT", "UNDERVEG", "UNDNWDY", "UNDWDY", "WALL",
        "WOODY", "ACTRANSP", "ARRIVE", "BANKWID", "BARWID", "BEAR", "BEAR2",
        "BOTTOMDOM", "BOTTOMSEC", "DLDLL", "DLDML", "DLDSL", "DMDLL",
        "DMDML", "DMDSL", "DSDLL", "DSDML", "DSDSL", "DXDLL", "DXDML",
        "DXDSL", "INCISED", "INTDTRAN", "LATDD", "LATDD_TOP", "LATDD2",
        "LATMM", "LATMM_TOP", "LATMM2", "LATSS", "LATSS_TOP", "LATSS2",
        "LEAVE", "LONGDD", "LONGDD_TOP", "LONGDD2", "LONGMM", "LONGMM_TOP",
        "LONGMM2", "LONGSS", "LONGSS_TOP", "LONGSS2", "POLE", "POLE",
        "SHOREDOM", "SHORESEC", "SLOPE_ND", "SONAR", "SONAR", "SUBOBS",
        "WAYPT", "WAYPT2", "WETWID", "WLDLL", "WLDML", "WLDSL", "WMDLL",
        "WMDML", "WMDSL", "WSDLL", "WSDML", "WSDSL", "WXDLL", "WXDML",
        "WXDSL", "BANKHGT", "BANKHT", "DISTANCE", "DISTANCE2", "DLDLL",
        "DLDML", "DLDSL", "DMDLL", "DMDML", "DMDSL", "DSDLL", "DSDML",
        "DSDSL", "DXDLL", "DXDML", "DXDSL", "INTDTRAN", "WLDLL", "WLDML",
        "WLDSL", "WMDLL", "WMDML", "WMDSL", "WSDLL", "WSDML", "WSDSL",
        "WXDLL", "WXDML", "WXDSL", "ALGAE", "ANGLE", "BANKWID", "BARE",
        "BARWID", "BOULDR", "BRUSH", "BUILD", "CANBTRE", "CANSTRE", "CANVEG",
        "DENSIOM", "DEPTH", "DIST_LB", "EMBED", "GCNWDY", "GCWDY", "INCISHGT",
        "LANDFL", "LOG", "LVTREE", "MACPHY", "MINE", "OVRHNG", "PARK",
        "PAST", "PAVE", "PIPES", "ROAD", "ROW", "SIZE_CLS", "STRUCT",
        "UNDCUT", "UNDERCUT", "UNDERVEG", "UNDNWDY", "UNDWDY", "WALL",
        "WETWID", "WOODY", "BANKFULL", "CONSTRNT", "FEATURES", "PATTERN",
        "PERCENT", "VALLEY", "VALLYBOX", "BEARING", "BEARING2", "BEARING3",
        "METHOD", "PROP", "PROP2", "PROP3", "SLOPE", "SLOPE", "SLOPE2",
        "SLOPE2", "SLOPE3", "SLOPE3", "BACKWATER", "BANK", "BAR_PRES",
        "BARWIDTH", "CHANUNCD", "DEP_POLE", "DEP_POLE", "DEP_SONR", "DEP_SONR",
        "DEPTH", "INCREMNT", "REACHLENGTH", "POOLFMCD", "SEDIMENT", "SIDCHN",
        "SIZE_CLS", "SNAG", "WETWIDTH", "DLDLL", "DLDML", "DLDSL", "DMDLL",
        "DMDML", "DMDSL", "DSDLL", "DSDML", "DSDSL", "DXDLL", "DXDML",
        "DXDSL", "OFF_CHAN", "SUB_5_7", "WLDLL", "WLDML", "WLDSL", "WMDLL",
        "WMDML", "WMDSL", "WSDLL", "WSDML", "WSDSL", "WXDLL", "WXDML",
        "WXDSL", "XSIZE_CLS", "COMP_VOL", "LOCATIONS", "SAMPLE_ID", "CHILLED",
        "SAMPLE_ID", "CHILLED", "SAMPLE_ID", "CHILLED", "COMP_VOL", "NO_TRAN",
        "SAMPLE_ID", "CHILLED", "COMP_VOL", "NO_TRAN", "SAMPLE_ID", "JAR_NO",
        "NO_TRAN", "SAMPLE_ID", "TYPE", "TSD01", "TSD02", "TSD03", "TSD04",
        "TSD05", "TSD06", "TSD07", "TSD08", "TSD09", "TSD10", "TSD11",
        "BELG", "BERW", "CHEM", "ENTE", "FTIS", "KICK", "PAPA", "PBIO",
        "PCHL", "PERI", "PHYT", "PPCP", "SAMPLED", "SNAG", "WCHL", "WPFC",
        "DATE_COL", "GENCOM", "NO_ACCESS", "NOT_SAMPLED", "NOT_SAMPLED_TEMP",
        "SAMP_STATUS", "SAMPLED", "SEDE", "SITE_ID", "SITESAMP", "STATE",
        "STATUS_COM", "TEAM_ID", "VALXSITE", "VISIT_NO", "XLAT_DD", "XLAT_DEG",
        "XLAT_MIN", "XLAT_SEC", "XLON_DD", "XLON_DEG", "XLON_MIN", "XLON_SEC",
        "XSTATUS", "FROZEN", "SAMPLE_ID", "VOLUME_FILTERED", "FROZEN",
        "SAMPLE_ID", "VOLUME_FILTERED", "SAMPLE_ID", "TIME_COLLECTED",
        "BATCHNO", "COMMENT", "FLAG", "LAB", "LAB_ID", "LINE", "PAGE",
        "PARAMETER", "REP", "RESULT", "SAMPLE_CAT", "SAMPLE_TYPE", "STATION",
        "TRANLINE", "TRANSDIR", "TRANSDIR", "TRANSDIR", "TRANSECT", "UNITS",
        "VERT", "DO_DISPLAYED_VALUE", "DO_DISPLAYED_VALUE", "OFF_CHAN",
        "CHANUNCD")
   ,LABEL = c("Agricultural: cropland (L/M/H)", "Agricultural: irrigation pumps (L/M/H)",
        "Agricultural: orchards (L/M/H)", "Agricultural: pasture (L/M/H)",
        "Agricultural: poultry (L/M/H)", "Agricultural: livestock (L/M/H)",
        "Agricultural, water withdrawal (L/M/H)", "Waterbody character appealing(5-1)unapp.",
        "Beaver signs (Absent/Rare/Common)", "Beaver flow modifications (None/Minor/Major)",
        "Dominant land use", "Dominant Forest age class", "General Comment1",
        "Industrial: commercial (L/M/H)", "Industrial: evidence of fire (L/M/H)",
        "Industrial: industrial plants (L/M/H)", "Industrial: logging (L/M/H)",
        "Industrial: mines/quarries (L/M/H)", "Industrial: odors (L/M/H)",
        "Industrial: oil/gas wells (L/M/H)", "Industrial: power plants (L/M/H)",
        "Stream mgt.: angling pressure (L/M/H)", "Stream mgt.: channelization (L/M/H)",
        "Stream mgt.: dams (L/M/H)", "Stream mgt.: dredging (L/M/H)",
        "Stream mgt.: drink h2o trtmt (L/M/H)", "Stream mgt.: fish stocking (L/M/H)",
        "Stream mgt.: liming (L/M/H)", "Stream mgt.: h2o level fluctuate (L/M/H)",
        "Waterbody character pristine (1-5)", "Reason for data change",
        "Recreational: surface films (L/M/H)", "Recreational: parks/campground (L/M/H)",
        "Recreational: primitive parks (L/M/H)", "Recreational: trash/litter (L/M/H)",
        "Recreational, hiking trails (L/M/H)", "Residental: bridges/culverts (L/M/H)",
        "Residental: construction (L/M/H)", "Residental: dumping (L/M/H)",
        "Residental: maintained lawns (L/M/H)", "Residental: pipes/drains (L/M/H)",
        "Residental: residences (L/M/H)", "Residental: roads (L/M/H)",
        "Residental, sewage trtmnt (L/M/H)", "Weather conditions", "Channel type: P, GL, RI, RA, O",
        "Dominant habitat (boatable): C, F, M, L, O", "Number of Jars",
        "Location across channel: L/R", "Sample preserved (Y/blank)",
        "Sample ID number.", "Secondary habitat (boatable): C, F, M, L, O",
        "Dominant substrate: F, G, C, O", "Channel type: P, GL, RI, RA, O",
        "Dominant edge (wadeable): L/R", "Number of Jars", "Location across channel: L, C, R.",
        "Sample preserved (Y/blank)", "Sample ID number.", "Dominant substrate: F, G, C, O",
        "Channel type: P, GL, RI, RA.", "Number of Jars", "Sample preserved (Y/blank)",
        "Sample ID number.", "Dominant substrate: F, G, C, O", "Instrument ID number.",
        "Instrument manufacturer and model.", "Instrument operator.",
        "Conductivity QCS description.", "Conductivity QCS measured.",
        "Conductivity QCS true (uS/cm).", "Conductivity STD1 description.",
        "Conductivity STD1 value.", "Conductivity STD2 description.",
        "Conductivity STD2 value.", "DO barometric pressure (mm Hg).",
        "DO calibration value.", "DO calibration value.", "DO displayed value.",
        "DO elevation.", "DO elevation.", "Barometric pressure (mm Hg)",
        "pH QCS description.", "pH QCS measured.", "pH QCS true.", "pH calibration STD 1 description.",
        "pH calibration STD 1 value.", "pH calibration STD 2 description.",
        "pH calibration STD 2 value.", "Temperature: sensor reading (C).",
        "Temperature: thermometer reading (C).", "Instrument ID number.",
        "Instrument manufacturer and model.", "Instrument operator.",
        "Conductivity QCS description.", "Conductivity QCS measured.",
        "Conductivity QCS true (uS/cm).", "Conductivity STD1 description.",
        "Conductivity STD1 value.", "Conductivity STD2 description.",
        "Conductivity STD2 value.", "DO barometric pressure (mm Hg).",
        "DO calibration value.", "DO calibration value.", "DO displayed value.",
        "DO elevation.", "DO elevation.", "Barometric pressure (mm Hg)",
        "pH QCS description.", "pH QCS measured.", "pH QCS true.", "pH calibration STD 1 description.",
        "pH calibration STD 1 value.", "pH calibration STD 2 description.",
        "pH calibration STD 2 value.", "Temperature: sensor reading (C).",
        "Temperature: thermometer reading (C).", "Sample chilled (Y/blank)",
        "Sample ID number.", "Sample chilled (Y/blank)", "Sample ID number.",
        "Depth at which sample was collected (m).", "Volume of water passed through filter 1 (mL).",
        "Volume of water passed through filter 2 (mL).", "Volume of water passed through filter 3 (mL).",
        "Volume of water passed through filter 4 (mL).", "Time filtration of samples finished.",
        "Time filtration of samples started.", "Sample ID number.", "Sample volume (mL)",
        "Time sample collected.", "Time of day sample was frozen.", "Depth at which sample was collected (m).",
        "Volume of water passed through filter 1 (mL).", "Volume of water passed through filter 2 (mL).",
        "Volume of water passed through filter 3 (mL).", "Volume of water passed through filter 4 (mL).",
        "Time filtration of samples finished.", "Time filtration of samples started.",
        "Sample ID number.", "Sample volume (mL)", "Time sample collected.",
        "Time of day sample was frozen.", "Bank chosen for reading",
        "Water clear to bottom: Y/blank.", "Water conductivity (uS/cm)",
        "Conductivity corrected to 25 C: Y/N", "Depth secchi disk disappears (m).",
        "Stream DO (mg/L)", "pH of water.", "Depth secchi disk reappears (m).",
        "Water temperature (C).", "Time of day (HH:MM).", "Bank chosen for reading",
        "Water conductivity (uS/cm)", "Conductivity corrected to 25 C: Y/N",
        "Stream DO (mg/L)", "pH of water.", "Water temperature (C).",
        "Time of day (HH:MM).", "Actual date of data collection", "Anomalies count",
        "Dominant subreach characteristics: bank cover", "Dominant subreach characteristics: other bank cover",
        "Total number of specimens", "Dominant subreach characteristics: cover type",
        "Dominant subreach characteristics: other cover type", "Stream depth (m)",
        "Distance sampled (m)", "Final fish count", "Number of mortalities",
        "Vertebrate common name", "Fished - none collected", "Photo taken: Y/blank",
        "Name of photo file.", "Shock time (s)", "Dominant subreach characteristics: other substrate",
        "Dominant subreach characteristics: substrate", "Tag number",
        "Fish length maximum (mm)", "Fish length minimum (mm)", "Total number vouchered",
        "Actual date of data collection", "Anomalies count", "Total number of specimens",
        "Final fish count", "Number of mortalities", "Vertebrate common name",
        "Photo taken: Y/blank", "Tag number", "Fish length maximum (mm)",
        "Fish length minimum (mm)", "Transect A: Y/Blank.", "Transect B: Y/Blank.",
        "Transect C: Y/Blank.", "Transect D: Y/Blank.", "Transect E: Y/Blank.",
        "Transect F: Y/Blank.", "Transect G: Y/Blank.", "Transect H: Y/Blank.",
        "Transect I: Y/Blank.", "Transect J: Y/Blank.", "Total number vouchered",
        "Common Name", "Sample frozen (Y/blank)", "Sample preserved (Y/blank)",
        "Sample ID number.", "Subreach fish tissue sample collected from.",
        "Total length (mm)", "Avg. width (m) for NBO method (OR --ft)",
        "Avg. width (m) for NBO method (OR --ft)", "Stream depth (cm) (OR--ft)",
        "Stream depth (cm) (OR--ft)", "Depth (cm) 1 for NBO method",
        "Depth (cm) 2 for NBO method", "Depth (cm) 3 for NBO method",
        "Depth (cm) 4 for NBO method", "Depth (cm) 5 for NBO method",
        "Depth (ft) 1 for NBO method", "Depth (ft) 2 for NBO method",
        "Depth (ft) 3 for NBO method", "Depth (ft) 4 for NBO method",
        "Depth (ft) 5 for NBO method", "Distance from bank (cm) (OR -- ft)",
        "Distance from bank (cm) (OR -- ft)", "Float distance (m) for NBO method",
        "Float distance (ft) for NBO method", "Method used to measure discharge",
        "Q value for stream discharge.", "Q value for stream discharge.",
        "Time for timed filling method (sec)", "Total time (sec) for NBO method",
        "Variation in velocity/depth regimes", "Variation in velocity/depth regimes",
        "Volume for timed filling method (L)", "Diameter breast height (m)",
        "Eurasian water milfoil: Y/blank", "Flowering rush: Y/blank",
        "Giant reed: Y/blank.", "Estimated height(m)", "Hydrilla: Y/blank",
        "Multi-flora rose: Y/blank", "No invasive species present", "No tree in range or sight: X/blank.",
        "Purple loosestrife: Y/blank.", "Salt cedar: Y/blank.", "Legacy tree species",
        "Leafy spurge: Y/blank.", "Legacy tree type", "Water hyacinth: Y/blank.",
        "Yellow floating heart: Y/blank", "Confidence in identification: Low/High",
        "Prevalence of invasive species", "Number of Jars", "Sample ID number.",
        "Snag type (natural/surrogate)", "Analyte.", "Holding time for sample after collection.",
        "Holding time exceeds recommended limit.", "Holding time units.",
        "Reporting limit alert", "Composite volume (mL)", "Sample frozen (Y/blank)",
        "Sample ID number.", "Number of transects sampled.", "Volume (mL) of sub. sample/filtered",
        "Composite volume (mL)", "Sample frozen (Y/blank)", "Sample ID number.",
        "Number of transects sampled.", "Volume (mL) of sub. sample/filtered",
        "Composite volume (mL)", "Sample frozen (Y/blank)", "Sample ID number.",
        "Number of transects sampled.", "Volume (mL) of sub. sample/filtered",
        "Composite volume (mL)", "Sample frozen (Y/blank)", "Sample ID number.",
        "Number of transects sampled.", "Volume (mL) of sub. sample/filtered",
        "Composite volume (mL)", "Sample frozen (Y/blank)", "Sample ID number.",
        "Number of transects sampled.", "Volume (mL) of sub. sample/filtered",
        "Composite volume (mL)", "Sample frozen (Y/blank)", "Sample ID number.",
        "Number of transects sampled.", "Volume (mL) of sub. sample/filtered",
        "Composite volume (mL)", "Sample preserved (Y/blank)", "Sample ID number.",
        "Number of transects sampled.", "Volume (mL) of sub. sample/filtered",
        "Composite volume (mL)", "Sample preserved (Y/blank)", "Sample ID number.",
        "Number of transects sampled.", "Volume (mL) of sub. sample/filtered",
        "Cover class for filamentous algae (0-4)", "Bank meas. angle (0-359 degree)",
        "Ground surface which is bare", "Cover class for in-chan. boulders (0-4)",
        "Cover class for woody debris <0.3m (0-4)", "Presence of buildings (0,P,C,B)",
        "Dens. of big (<0.3m DBH) trees in canopy.", "Dens. of small (>0.3 DBH) trees in canopy.",
        "Type of canopy veg", "Level of channel constraint (C/U/B/N)",
        "Count using spherical densiometer = 0-17", "Ground cover (<0.5m) by nonwoody veg",
        "Ground cover (<0.5m) by woody veg", "Human influence landfill",
        "Presence of logging operations (0,P,C,B)", "Cover class for live trees/roots (0-4)",
        "Cover class for macrophyton (0-4)", "Human influence mining activity",
        "Presence of park or lawn (0,P,C,B)", "Human influence pasture",
        "Human influence pavement", "Human influence pipe", "Presence of road/railroad (0,P,C,B)",
        "Presence of row crops (0,P,C,B)", "Can readily see overbank (YES/NO)",
        "Distance from shore to R. vegetation (m)", "Cover class for artificial struct. (0-4)",
        "Cover class for bank undercuts (0-4)", "Distance of bank undercut by water (m)",
        "Understory veg type", "Understory (0.5-5m) cover by non-woody veg",
        "Understory (0.5-5m) cover by woody veg", "Presence of wall/dam/other (0,P,C,B)",
        "Cover class for woody debris >0.3m (0-4)", "Actual transect spacing (m).",
        "Time of arrival for GPS fix", "Bank meas. bankfull width (m)",
        "Bank meas. bar width (m)", "Main backsite bearing (0-359 degree)",
        "1st supplemental backsite bearing (0-359 degree)", "Bottom dominant substrate",
        "Bottom secondary substrate", "Count of dry large dia long length lwd",
        "Count of dry large dia med. length lwd", "Count of dry large dia short length lwd",
        "Count of dry med. dia long length lwd", "Count of dry med. dia med. length lwd",
        "Count of dry med. dia short length lwd", "Count of dry small dia long length lwd",
        "Count of dry small dia med. length lwd", "Count of dry small dia short length lwd",
        "Count of dry xlarge dia long length lwd", "Count of dry xlarge dia med. length lwd",
        "Count of dry xlarge dia short length lwd", "Bank meas. incised height (m)",
        "Intended transect spacing (m).", "Transect latitude for slope/bearing/distance - degrees (Main)",
        "Transect latitude - degrees (Midstream or Bank)", "Transect latitude for slope/bearing/distance - degrees (1st supplemental)",
        "Transect latitude for slope/bearing/distance - minutes (Main)",
        "Transect latitude - minutes (Midstream or Bank)", "Transect latitude for slope/bearing/distance - minutes (1st supplemental)",
        "Transect latitude for slope/bearing/distance - seconds (Main)",
        "Transect latitude - seconds (Midstream or Bank)", "Transect latitude for slope/bearing/distance - seconds (1st supplemental)",
        "Time left for GPS fix", "Transect longitude for slope/bearing/distance - degrees (Main)",
        "Transect longitude - degrees (Midstream or Bank)", "Transect longitude for slope/bearing/distance - degrees (1st supplemental)",
        "Transect longitude for slope/bearing/distance - minutes (Main)",
        "Transect longitude - minutes (Midstream or Bank)", "Transect longitude for slope/bearing/distance - minutes (1st supplemental)",
        "Transect longitude for slope/bearing/distance - seconds (Main)",
        "Transect longitude - seconds (Midstream or Bank)", "Transect longitude for slope/bearing/distance - seconds (1st supplemental)",
        "Depth by pole", "Depth by pole", "Dominate shore substrate",
        "Secondary shore substrate", "Slope and bearing not determined",
        "Depth by sonar", "Depth by sonar", "Substrate from (JUDGement/OBServation)",
        "Waypoint number (Main)", "Waypoint number (1st supplemental)",
        "Wetted width (m)", "Count of wet large dia long length lwd",
        "Count of wet large dia med. length lwd", "Count of wet large dia short length lwd",
        "Count of wet med. dia long length lwd", "Count of wet med. dia med. length lwd",
        "Count of wet med. dia short length lwd", "Count of wet small dia long length lwd",
        "Count of wet small dia med. length lwd", "Count of wet small dia short length lwd",
        "Count of wet xlarge dia long length lwd", "Count of wet xlarge dia med length lwd",
        "Count of wet xlarge dia shrt length lwd", "Bank meas. bankfull height (m)",
        "Bank meas. bankfull height (m)", "Dist from river/stream wetted margin (m) (Main)",
        "Dist from river/stream wetted margin (m) (1st supplemental)",
        "Count of dry large dia long length lwd", "Count of dry large dia med. length lwd",
        "Count of dry large dia short length lwd", "Count of dry med. dia long length lwd",
        "Count of dry med. dia med. length lwd", "Count of dry med. dia short length lwd",
        "Count of dry small dia long length lwd", "Count of dry small dia med. length lwd",
        "Count of dry small dia short length lwd", "Count of dry xlarge dia long length lwd",
        "Count of dry xlarge dia med. length lwd", "Count of dry xlarge dia short length lwd",
        "Intended transect spacing (m).", "Count of wet large dia long length lwd",
        "Count of wet large dia med. length lwd", "Count of wet large dia short length lwd",
        "Count of wet med. dia long length lwd", "Count of wet med. dia med. length lwd",
        "Count of wet med. dia short length lwd", "Count of wet small dia long length lwd",
        "Count of wet small dia med. length lwd", "Count of wet small dia short length lwd",
        "Count of wet xlarge dia long length lwd", "Count of wet xlarge dia med length lwd",
        "Count of wet xlarge dia shrt length lwd", "Cover class for filamentous algae (0-4)",
        "Bank meas. angle (0-359 degree)", "Bank meas. bankfull width (m)",
        "Ground surface which is bare", "Bank meas. bar width (m)", "Cover class for in-chan. boulders (0-4)",
        "Cover class for woody debris <0.3m (0-4)", "Presence of buildings (0,P,C,B)",
        "Dens. of big (<0.3m DBH) trees in canopy.", "Dens. of small (>0.3 DBH) trees in canopy.",
        "Type of canopy veg", "Count using spherical densiometer = 0-17",
        "Stream depth (cm)", "Distance from the left bank (m)", "% embeddedness of gravel sized substrate",
        "Ground cover (<0.5m) by nonwoody veg", "Ground cover (<0.5m) by woody veg",
        "Bank meas. incised height (m)", "Human influence landfill",
        "Presence of logging operations (0,P,C,B)", "Cover class for live trees/roots (0-4)",
        "Cover class for macrophyton (0-4)", "Human influence mining activity",
        "Cover class for overhanging veg (0-4)", "Presence of park or lawn (0,P,C,B)",
        "Human influence pasture", "Human influence pavement", "Human influence pipe",
        "Presence of road/railroad (0,P,C,B)", "Presence of row crops (0,P,C,B)",
        "Substrate particle size class", "Cover class for artificial struct. (0-4)",
        "Cover class for bank undercuts (0-4)", "Distance of bank undercut by water (m)",
        "Understory veg type", "Understory (0.5-5m) cover by non-woody veg",
        "Understory (0.5-5m) cover by woody veg", "Presence of wall/dam/other (0,P,C,B)",
        "Wetted width (m)", "Cover class for woody debris >0.3m (0-4)",
        "Bankfull width (m)", "Channel constraint.", "Features constraining channel.",
        "Channel pattern.", "% of length in contact with constraint",
        "Valley width (vis. estimate) (m)", "Valley width greater than visible:Y/blank",
        "Main bearing (0-359 degree)", "1st supplemental bearing (0-359 degree)",
        "2nd supplemental bearing (0-359 degree)", "Method used to measure slope.",
        "Main proportion - streams", "1st supplemental proportion - streams",
        "2nd supplemental proportion - streams", "Main slope (%) OR Elev. Diff - Stream",
        "Main slope (%) OR Elev. Diff - Stream", "1st supplemental slope (%) OR Elev. Diff - Stream",
        "1st supplemental slope (%) OR Elev. Diff - Stream", "2nd supplemental slope (%) OR Elev. Diff - Stream",
        "2nd supplemental slope (%) OR Elev. Diff - Stream", "Backwater (Y/N)",
        "Bank chosen for reading (Right/Left)", "Bar present (Y/N)",
        "Bar width (m)", "Channel unit code", "Depth by pole", "Depth by pole",
        "Depth by sonar", "Depth by sonar", "Thalweg depth (cm)", "Uniform increment between transects (m)",
        "Total reach length (m).", "Pool form code", "Soft/small sediment (Y/N)",
        "Side channel (Y/N)", "Substrate particle size class", "Snag (Y/N)",
        "Wetted width (m)", "Count of dry large dia long length lwd",
        "Count of dry large dia med. length lwd", "Count of dry large dia short length lwd",
        "Count of dry med. dia long length lwd", "Count of dry med. dia med. length lwd",
        "Count of dry med. dia short length lwd", "Count of dry small dia long length lwd",
        "Count of dry small dia med. length lwd", "Count of dry small dia short length lwd",
        "Count of dry xlarge dia long length lwd", "Count of dry xlarge dia med. length lwd",
        "Count of dry xlarge dia short length lwd", "Presence of off channel/backwater (Y/N)",
        "Extra substrate station (5 or 7)", "Count of wet large dia long length lwd",
        "Count of wet large dia med. length lwd", "Count of wet large dia short length lwd",
        "Count of wet med. dia long length lwd", "Count of wet med. dia med. length lwd",
        "Count of wet med. dia short length lwd", "Count of wet small dia long length lwd",
        "Count of wet small dia med. length lwd", "Count of wet small dia short length lwd",
        "Count of wet xlarge dia long length lwd", "Count of wet xlarge dia med length lwd",
        "Count of wet xlarge dia shrt length lwd", "Substrate particle size class",
        "Composite volume (mL)", "Number of locations sampled (0-5)",
        "Sample ID number.", "Sample chilled (Y/blank)", "Sample ID number.",
        "Sample chilled (Y/blank)", "Sample ID number.", "Sample chilled (Y/blank)",
        "Composite volume (mL)", "Number of transects sampled.", "Sample ID number.",
        "Sample chilled (Y/blank)", "Composite volume (mL)", "Number of transects sampled.",
        "Sample ID number.", "Number of Jars", "Number of transects sampled.",
        "Sample ID number.", "Snag type (natural/surrogate)", "Scouring:recent deveg of corridor",
        "Scouring:substrate not imbricated", "Scouring:little evid of pool-riffle",
        "Scouring:scoured down to bedrock", "Scouring:berms above bankfull level",
        "Scouring:massive deposits downstream", "Scouring:bark scars on riparian trees",
        "Scouring:trees fallen into channel", "Deposits:massive deposits in reach",
        "Deposits:new Matrix Supported deposits", "No evidence of torrenct scouring/depos",
        "Transect benthos sample collected (Y/blank)", "Benthos - reachwide sample collected (Y/blank)",
        "Water chemistry sample collected (Y/blank)", "Enterococci sample collected (Y/blank)",
        "Fish tissue sample collected (Y/blank)", "Kick sample collected (Y/blank) (LM)",
        "Periphyton - APA sample collected (Y/blank)", "Periphyton - BIO sample collected (Y/blank)",
        "Periphtyon - Chorophyll sample collected (Y/blank)", "Periphyton - Assmeblage ID sample collected (Y/blank)",
        "Phytoplankton sample collected (Y/blank) (LM)", "Water chemistry PPCP sample collected (Y/blank)",
        "Sample collected: Y/N.", "Snag sample collected (Y/blank) (LM)",
        "Water column clorophyll sample collected (Y/blank)", "Water PFC sample collected (Y/blank)",
        "Date of data collection in field", "General comments.", "Reason the site is inaccessable.",
        "Reason site permanently non-sampleable.", "Site temporarily non-sampleable.",
        "No samples taken (NoSamps/blank)", "Method used to sample site.",
        "Sediment chemistry/enzymes sample collected (Y/blank)", "Site ID",
        "Was site sampled: Y/N.", "State in which site is located.",
        "IM comment on site status.", "Field personnel identifier", "Sample method/Nonsamp. reason",
        "Number identifying which visit this is", "Index site latitude in decimal degrees.",
        "Index site latitude (deg)", "Index site latitude (min)", "Index site latitude (sec)",
        "Index site longitude in decimal degrees.", "Index site longitude (deg)",
        "Index site longitude (min)", "Index site longitude (sec)", "X-Site Sampling Status",
        "Sample frozen (Y/blank)", "Sample ID number.", "Volume of sample filtered (mL).",
        "Sample frozen (Y/blank)", "Sample ID number.", "Volume of sample filtered (mL).",
        "Sample ID number.", "Time sample collected.", "Batch number created by Teleform when site was entered.",
        "Comment text entered by field personnel", "Flag", "Lab which processed sample.",
        "Identification number used by lab.", "Line number", "Page number",
        "Identifier variables.", "Repetition number (1/2/3)", "Measurement associated with PARAMETER variable.",
        "Sample category (P/D)", "Sample type.", "Station number (0-14)",
        "Location of GPS reading at transect", "Location along transect = RT,LF",
        "Location along transect = RT,RC,CT,LC,LF,NONE", "Location along transect = CD,CL,CR,CU,LF,RT,DN,UP,CT",
        "Transect label A-K (sidechannels XA-XK)", "Units of RESULT measurement.",
        "Vertebrate sample collected (Y/blank)", "DO displayed balue.",
        "DO displayed value.", "Presence of off channel/backwater (Y/N)",
        "Channel habitat")
   ,UNITS = c("NONE", "NONE", "NONE", "NONE",
        "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE",
        "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE",
        "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE",
        "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE",
        "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE",
        "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE",
        "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE",
        "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE",
        "NONE", "NONE", "US/CM", "NONE", "NONE", "NONE", "NONE", "MMHG",
        "MG/L", "PERCENT", "MG/L", "FT", "M", "MMHG", "NONE", "NONE",
        "NONE", "NONE", "NONE", "NONE", "NONE", "C", "C", "NONE", "NONE",
        "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE",
        "MMHG", "MG/L", "PERCENT", "MG/L", "FT", "M", "NONE", "NONE",
        "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "C", "C", "NONE",
        "NONE", "NONE", "NONE", "M", "ML", "ML", "ML", "ML", "NONE",
        "NONE", "NONE", "ML", "NONE", "NONE", "M", "ML", "ML", "ML",
        "ML", "NONE", "NONE", "NONE", "ML", "NONE", "NONE", "NONE", "NONE",
        "NONE", "NONE", "M", "NONE", "NONE", "M", "NONE", "NONE", "NONE",
        "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE",
        "NONE", "NONE", "NONE", "NONE", "NONE", "M", "M", "NONE", "NONE",
        "NONE", "NONE", "NONE", "NONE", "S", "NONE", "NONE", "NONE",
        "MM", "MM", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE",
        "NONE", "NONE", "MM", "MM", "NONE", "NONE", "NONE", "NONE", "NONE",
        "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE",
        "NONE", "NONE", "NONE", "MM", "M", "FT", "FT", "CM", "CM", "CM",
        "CM", "CM", "CM", "FT", "FT", "FT", "FT", "FT", "CM", "FT", "M",
        "FT", "NONE", "CFS", "M3/S", "SEC", "SEC", "FT/S", "M/S", "L",
        "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE",
        "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE",
        "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE",
        "NONE", "NONE", "ML", "NONE", "NONE", "NONE", "ML", "ML", "NONE",
        "NONE", "NONE", "ML", "ML", "NONE", "NONE", "NONE", "ML", "ML",
        "NONE", "NONE", "NONE", "ML", "ML", "NONE", "NONE", "NONE", "ML",
        "ML", "NONE", "NONE", "NONE", "ML", "ML", "NONE", "NONE", "NONE",
        "ML", "ML", "NONE", "NONE", "NONE", "ML", "NONE", "NONE", "NONE",
        "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE",
        "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE",
        "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "M", "NONE",
        "NONE", "M", "NONE", "NONE", "NONE", "NONE", "NONE", "M", "NONE",
        "M", "M", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE",
        "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE",
        "NONE", "M", "M", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE",
        "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE",
        "NONE", "NONE", "NONE", "NONE", "NONE", "M", "FT", "NONE", "NONE",
        "NONE", "M", "FT", "NONE", "NONE", "NONE", "M", "NONE", "NONE",
        "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE",
        "NONE", "NONE", "M", "M", "M", "M", "NONE", "NONE", "NONE", "NONE",
        "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE",
        "M", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE",
        "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "M",
        "NONE", "M", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE",
        "NONE", "CM", "M", "NONE", "NONE", "NONE", "M", "NONE", "NONE",
        "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE",
        "NONE", "NONE", "NONE", "NONE", "NONE", "M", "NONE", "NONE",
        "NONE", "NONE", "M", "NONE", "M", "NONE", "NONE", "NONE", "NONE",
        "M", "NONE", "NONE", "NONE", "NONE", "NONE", "PERCENT", "PERCENT",
        "PERCENT", "PERCENT", "CM", "PERCENT", "CM", "PERCENT", "CM",
        "NONE", "NONE", "NONE", "M", "NONE", "M", "FT", "FT", "M", "CM",
        "M", "M", "NONE", "NONE", "NONE", "NONE", "NONE", "M", "NONE",
        "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE",
        "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE",
        "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE",
        "NONE", "NONE", "ML", "NONE", "NONE", "NONE", "NONE", "NONE",
        "NONE", "NONE", "ML", "NONE", "NONE", "NONE", "ML", "NONE", "NONE",
        "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE",
        "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE",
        "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE",
        "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE",
        "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE",
        "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE",
        "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE",
        "NONE", "ML", "NONE", "NONE", "ML", "NONE", "NONE", "NONE", "NONE",
        "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE",
        "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE", "NONE",
        "NONE", "NONE", "PERCENT", "PERCENT", "NONE", "NONE")
   ,SAMPLE_TYPE = c("ASSE",
        "ASSE", "ASSE", "ASSE", "ASSE", "ASSE", "ASSE", "ASSE", "ASSE",
        "ASSE", "ASSE", "ASSE", "ASSE", "ASSE", "ASSE", "ASSE", "ASSE",
        "ASSE", "ASSE", "ASSE", "ASSE", "ASSE", "ASSE", "ASSE", "ASSE",
        "ASSE", "ASSE", "ASSE", "ASSE", "ASSE", "ASSE", "ASSE", "ASSE",
        "ASSE", "ASSE", "ASSE", "ASSE", "ASSE", "ASSE", "ASSE", "ASSE",
        "ASSE", "ASSE", "ASSE", "ASSE", "BELGB", "BELGB", "BELGB", "BELGB",
        "BELGB", "BELGB", "BELGB", "BELGB", "BELGW", "BELGW", "BELGW",
        "BELGW", "BELGW", "BELGW", "BELGW", "BERWW", "BERWW", "BERWW",
        "BERWW", "BERWW", "CALI", "CALI", "CALI", "CALI", "CALI", "CALI",
        "CALI", "CALI", "CALI", "CALI", "CALI", "CALI", "CALI", "CALI",
        "CALI", "CALI", "CALI", "CALI", "CALI", "CALI", "CALI", "CALI",
        "CALI", "CALI", "CALI", "CALI", "CALI", "CALI", "CALI", "CALI",
        "CALI", "CALI", "CALI", "CALI", "CALI", "CALI", "CALI", "CALI",
        "CALI", "CALI", "CALI", "CALI", "CALI", "CALI", "CALI", "CALI",
        "CALI", "CALI", "CALI", "CALI", "CALI", "CALI", "CHEMB", "CHEMB",
        "CHEMW", "CHEMW", "ENTEB", "ENTEB", "ENTEB", "ENTEB", "ENTEB",
        "ENTEB", "ENTEB", "ENTEB", "ENTEB", "ENTEB", "ENTEB", "ENTEW",
        "ENTEW", "ENTEW", "ENTEW", "ENTEW", "ENTEW", "ENTEW", "ENTEW",
        "ENTEW", "ENTEW", "ENTEW", "FIELDMEAS", "FIELDMEAS", "FIELDMEAS",
        "FIELDMEAS", "FIELDMEAS", "FIELDMEAS", "FIELDMEAS", "FIELDMEAS",
        "FIELDMEAS", "FIELDMEAS", "FIELDMEAS", "FIELDMEAS", "FIELDMEAS",
        "FIELDMEAS", "FIELDMEAS", "FIELDMEAS", "FIELDMEAS", "FISHB",
        "FISHB", "FISHB", "FISHB", "FISHB", "FISHB", "FISHB", "FISHB",
        "FISHB", "FISHB", "FISHB", "FISHB", "FISHB", "FISHB", "FISHB",
        "FISHB", "FISHB", "FISHB", "FISHB", "FISHB", "FISHB", "FISHB",
        "FISHW", "FISHW", "FISHW", "FISHW", "FISHW", "FISHW", "FISHW",
        "FISHW", "FISHW", "FISHW", "FISHW", "FISHW", "FISHW", "FISHW",
        "FISHW", "FISHW", "FISHW", "FISHW", "FISHW", "FISHW", "FISHW",
        "FISHTV", "FISHTV", "FISHTV", "FISHTV", "FISHTV", "FISHTV", "FLOW",
        "FLOW", "FLOW", "FLOW", "FLOW", "FLOW", "FLOW", "FLOW", "FLOW",
        "FLOW", "FLOW", "FLOW", "FLOW", "FLOW", "FLOW", "FLOW", "FLOW",
        "FLOW", "FLOW", "FLOW", "FLOW", "FLOW", "FLOW", "FLOW", "FLOW",
        "FLOW", "INVA", "INVA", "INVA", "INVA", "INVA", "INVA", "INVA",
        "INVA", "INVA", "INVA", "INVA", "INVA", "INVA", "INVA", "INVA",
        "INVA", "INVA", "INVA", "KICK", "KICK", "KICK", "LABRESULT",
        "LABRESULT", "LABRESULT", "LABRESULT", "LABRESULT", "PAPAB",
        "PAPAB", "PAPAB", "PAPAB", "PAPAB", "PAPAW", "PAPAW", "PAPAW",
        "PAPAW", "PAPAW", "PBIOB", "PBIOB", "PBIOB", "PBIOB", "PBIOB",
        "PBIOW", "PBIOW", "PBIOW", "PBIOW", "PBIOW", "PCHLB", "PCHLB",
        "PCHLB", "PCHLB", "PCHLB", "PCHLW", "PCHLW", "PCHLW", "PCHLW",
        "PCHLW", "PERIB", "PERIB", "PERIB", "PERIB", "PERIB", "PERIW",
        "PERIW", "PERIW", "PERIW", "PERIW", "PHAB_CHANB", "PHAB_CHANB",
        "PHAB_CHANB", "PHAB_CHANB", "PHAB_CHANB", "PHAB_CHANB", "PHAB_CHANB",
        "PHAB_CHANB", "PHAB_CHANB", "PHAB_CHANB", "PHAB_CHANB", "PHAB_CHANB",
        "PHAB_CHANB", "PHAB_CHANB", "PHAB_CHANB", "PHAB_CHANB", "PHAB_CHANB",
        "PHAB_CHANB", "PHAB_CHANB", "PHAB_CHANB", "PHAB_CHANB", "PHAB_CHANB",
        "PHAB_CHANB", "PHAB_CHANB", "PHAB_CHANB", "PHAB_CHANB", "PHAB_CHANB",
        "PHAB_CHANB", "PHAB_CHANB", "PHAB_CHANB", "PHAB_CHANB", "PHAB_CHANB",
        "PHAB_CHANB", "PHAB_CHANB", "PHAB_CHANBFRONT", "PHAB_CHANBFRONT",
        "PHAB_CHANBFRONT", "PHAB_CHANBFRONT", "PHAB_CHANBFRONT", "PHAB_CHANBFRONT",
        "PHAB_CHANBFRONT", "PHAB_CHANBFRONT", "PHAB_CHANBFRONT", "PHAB_CHANBFRONT",
        "PHAB_CHANBFRONT", "PHAB_CHANBFRONT", "PHAB_CHANBFRONT", "PHAB_CHANBFRONT",
        "PHAB_CHANBFRONT", "PHAB_CHANBFRONT", "PHAB_CHANBFRONT", "PHAB_CHANBFRONT",
        "PHAB_CHANBFRONT", "PHAB_CHANBFRONT", "PHAB_CHANBFRONT", "PHAB_CHANBFRONT",
        "PHAB_CHANBFRONT", "PHAB_CHANBFRONT", "PHAB_CHANBFRONT", "PHAB_CHANBFRONT",
        "PHAB_CHANBFRONT", "PHAB_CHANBFRONT", "PHAB_CHANBFRONT", "PHAB_CHANBFRONT",
        "PHAB_CHANBFRONT", "PHAB_CHANBFRONT", "PHAB_CHANBFRONT", "PHAB_CHANBFRONT",
        "PHAB_CHANBFRONT", "PHAB_CHANBFRONT", "PHAB_CHANBFRONT", "PHAB_CHANBFRONT",
        "PHAB_CHANBFRONT", "PHAB_CHANBFRONT", "PHAB_CHANBFRONT", "PHAB_CHANBFRONT",
        "PHAB_CHANBFRONT", "PHAB_CHANBFRONT", "PHAB_CHANBFRONT", "PHAB_CHANBFRONT",
        "PHAB_CHANBFRONT", "PHAB_CHANBFRONT", "PHAB_CHANBFRONT", "PHAB_CHANBFRONT",
        "PHAB_CHANBFRONT", "PHAB_CHANBFRONT", "PHAB_CHANBFRONT", "PHAB_CHANBFRONT",
        "PHAB_CHANBFRONT", "PHAB_CHANBFRONT", "PHAB_CHANBFRONT", "PHAB_CHANBFRONT",
        "PHAB_CHANBFRONT", "PHAB_CHANBFRONT", "PHAB_CHANBFRONT", "PHAB_CHANBFRONT",
        "PHAB_CHANBFRONT", "PHAB_CHANBFRONT", "PHAB_CHANFRONT", "PHAB_CHANFRONT",
        "PHAB_CHANBFRONT", "PHAB_CHANBFRONT", "PHAB_CHANFRONT", "PHAB_CHANFRONT",
        "PHAB_CHANFRONT", "PHAB_CHANFRONT", "PHAB_CHANFRONT", "PHAB_CHANFRONT",
        "PHAB_CHANFRONT", "PHAB_CHANFRONT", "PHAB_CHANFRONT", "PHAB_CHANFRONT",
        "PHAB_CHANFRONT", "PHAB_CHANFRONT", "PHAB_CHANFRONT", "PHAB_CHANFRONT",
        "PHAB_CHANFRONT", "PHAB_CHANFRONT", "PHAB_CHANFRONT", "PHAB_CHANFRONT",
        "PHAB_CHANFRONT", "PHAB_CHANFRONT", "PHAB_CHANFRONT", "PHAB_CHANFRONT",
        "PHAB_CHANFRONT", "PHAB_CHANFRONT", "PHAB_CHANFRONT", "PHAB_CHANW",
        "PHAB_CHANW", "PHAB_CHANW", "PHAB_CHANW", "PHAB_CHANW", "PHAB_CHANW",
        "PHAB_CHANW", "PHAB_CHANW", "PHAB_CHANW", "PHAB_CHANW", "PHAB_CHANW",
        "PHAB_CHANW", "PHAB_CHANW", "PHAB_CHANW", "PHAB_CHANW", "PHAB_CHANW",
        "PHAB_CHANW", "PHAB_CHANW", "PHAB_CHANW", "PHAB_CHANW", "PHAB_CHANW",
        "PHAB_CHANW", "PHAB_CHANW", "PHAB_CHANW", "PHAB_CHANW", "PHAB_CHANW",
        "PHAB_CHANW", "PHAB_CHANW", "PHAB_CHANW", "PHAB_CHANW", "PHAB_CHANW",
        "PHAB_CHANW", "PHAB_CHANW", "PHAB_CHANW", "PHAB_CHANW", "PHAB_CHANW",
        "PHAB_CHANW", "PHAB_CHANW", "PHAB_CHANW", "PHAB_CHANW", "PHAB_CHCON",
        "PHAB_CHCON", "PHAB_CHCON", "PHAB_CHCON", "PHAB_CHCON", "PHAB_CHCON",
        "PHAB_CHCON", "PHAB_SLOPE", "PHAB_SLOPE", "PHAB_SLOPE", "PHAB_SLOPE",
        "PHAB_SLOPE", "PHAB_SLOPE", "PHAB_SLOPE", "PHAB_SLOPE", "PHAB_SLOPE",
        "PHAB_SLOPE", "PHAB_SLOPE", "PHAB_SLOPE", "PHAB_SLOPE", "PHAB_THALW",
        "PHAB_THAL", "PHAB_THALW", "PHAB_THALW", "PHAB_THALW", "PHAB_THAL",
        "PHAB_THAL", "PHAB_THAL", "PHAB_THAL", "PHAB_THALW", "PHAB_THALW",
        "PHAB_THALW", "PHAB_THALW", "PHAB_THALW", "PHAB_THALW", "PHAB_THAL",
        "PHAB_THAL", "PHAB_THALW", "PHAB_THALW", "PHAB_THALW", "PHAB_THALW",
        "PHAB_THALW", "PHAB_THALW", "PHAB_THALW", "PHAB_THALW", "PHAB_THALW",
        "PHAB_THALW", "PHAB_THALW", "PHAB_THALW", "PHAB_THALW", "PHAB_THALW",
        "PHAB_THALW", "PHAB_THALW", "PHAB_THALW", "PHAB_THALW", "PHAB_THALW",
        "PHAB_THALW", "PHAB_THALW", "PHAB_THALW", "PHAB_THALW", "PHAB_THALW",
        "PHAB_THALW", "PHAB_THALW", "PHAB_THALW", "PHAB_THALW", "PHYTB",
        "PHYTB", "PHYTB", "PPCPB", "PPCPB", "PPCPW", "PPCPW", "SEDEB",
        "SEDEB", "SEDEB", "SEDEB", "SEDEW", "SEDEW", "SEDEW", "SEDEW",
        "SNAGB", "SNAGB", "SNAGB", "SNAGB", "TORR", "TORR", "TORR", "TORR",
        "TORR", "TORR", "TORR", "TORR", "TORR", "TORR", "TORR", "VERIF",
        "VERIF", "VERIF", "VERIF", "VERIF", "VERIF", "VERIF", "VERIF",
        "VERIF", "VERIF", "VERIF", "VERIF", "VERIF", "VERIF", "VERIF",
        "VERIF", "VERIF", "VERIF", "VERIF", "VERIF", "VERIF", "VERIF",
        "VERIF", "VERIF", "VERIF", "VERIF", "VERIF", "VERIF", "VERIF",
        "VERIF", "VERIF", "VERIF", "VERIF", "VERIF", "VERIF", "VERIF",
        "VERIF", "VERIF", "VERIF", "VERIF", "WCHLB", "WCHLB", "WCHLB",
        "WCHLW", "WCHLW", "WCHLW", "WPFCB", "WPFCB", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
        "CALI", "CALI", "PHAB_THAL", "PHAB_THAL")
   ,RANGETYPE = c("",
        "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "", "", "", "", "TIME", "TIME",
        "", "", "TIME", "TIME", "", "", "", "", "", "TIME", "TIME", "",
        "", "TIME", "TIME", "", "", "", "", "", "", "", "", "", "TIME",
        "", "", "", "", "", "", "TIME", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "TIME", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "TIME", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "", "", "", "TIME", "", "",
        "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
        "", "", NA, NA, NA, NA)
   ,RANGELOW = c(NA, NA, NA, NA, NA, NA,
        NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,
        NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,
        NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,
        NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,
        NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,
        NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,
        NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,
        NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,
        NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 0.1, NA,
        NA, 0.1, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,
        NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,
        NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,
        NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 1, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, NA, NA, NA, NA, NA, NA, NA,
        NA, NA, NA, NA, NA, 0.1, NA, NA, NA, 1, NA, NA, NA, NA, NA, NA,
        NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 500,
        NA, NA, NA, NA, 500, NA, NA, NA, NA, 500, NA, NA, NA, NA, 500,
        NA, NA, NA, NA, 500, NA, NA, NA, NA, 500, NA, NA, NA, NA, 500,
        NA, NA, NA, NA, 500, NA, NA, NA, NA, NA, 0, NA, NA, NA, NA, NA,
        NA, NA, NA, 0, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,
        NA, NA, 0, NA, NA, 0, NA, NA, NA, NA, NA, 50, NA, 5, 0, 0, 0,
        NA, NA, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, NA, 25, 25, 25,
        0, 0, 0, 0, 0, 0, NA, 67, 67, 67, 0, 0, 0, 0, 0, 0, 0, 0, NA,
        NA, NA, 0, 0, NA, NA, NA, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, NA, NA, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, NA, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, NA, 0, 0.5, NA, 0, NA, NA, NA,
        NA, NA, NA, 0, 0, 0, 0, NA, NA, 0, NA, NA, NA, NA, NA, NA, NA,
        NA, NA, NA, NA, NA, NA, NA, NA, 0, NA, NA, NA, NA, 0, NA, 0.5,
        NA, NA, NA, 0, 10, NA, 0, 0, 0, NA, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        NA, NA, NA, NA, NA, 0.1, 0.1, 0.1, 0.1, 0, NA, NA, NA, NA, NA,
        NA, NA, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, NA, 5, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, NA, 500, 0, NA, NA, NA, NA, NA, NA,
        500, NA, NA, NA, 500, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,
        NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,
        NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,
        NA, NA, NA, NA, NA, NA, 25, 25, 0, 0, 67, 67, 0, 0, NA, NA, NA,
        NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,
        NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA)
   ,RANGEHIGH = c(NA,
        NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,
        NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,
        NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,
        NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,
        NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,
        NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,
        NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,
        NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,
        NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,
        NA, NA, 5, NA, NA, 5, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,
        NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,
        NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,
        NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,
        100, 100, 2, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, NA,
        NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 1.5, NA, NA, NA,
        30, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,
        NA, NA, NA, NA, NA, NA, 2000, NA, NA, NA, NA, 2000, NA, NA, NA,
        NA, 2000, NA, NA, NA, NA, 2000, NA, NA, NA, NA, 2000, NA, NA,
        NA, NA, 2000, NA, NA, NA, NA, 2000, NA, NA, NA, NA, 2000, NA,
        NA, NA, NA, NA, 120, NA, NA, NA, NA, NA, NA, NA, NA, 17, NA,
        NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 100, NA,
        NA, 4, NA, NA, NA, NA, NA, 1000, NA, 300, 20, 359, 359, NA, NA,
        5, 5, 10, 10, 15, 15, 15, 20, 30, 5, 5, 5, 10, NA, 60, 60, 60,
        59, 59, 59, 59.9, 59.9, 59.9, NA, 124, 124, 124, 59, 59, 59,
        59.9, 59.9, 59.9, 3, 9, NA, NA, NA, 5, 15, NA, NA, NA, 150, 5,
        10, 15, 10, 15, 25, 10, 15, 20, 5, 5, 5, 2, 5, NA, NA, 5, 5,
        10, 10, 15, 15, 15, 20, 30, 5, 5, 5, NA, 5, 10, 15, 10, 15, 25,
        10, 15, 20, 5, 5, 5, NA, 120, 99, NA, 9.9, NA, NA, NA, NA, NA,
        NA, 17, 200, 2000, 100, NA, NA, 5, NA, NA, NA, NA, NA, NA, NA,
        NA, NA, NA, NA, NA, NA, NA, NA, 1, NA, NA, NA, NA, 50, NA, 200,
        NA, NA, NA, 100, 2000, NA, 359, 359, 359, NA, 100, 100, 100,
        5, 50, 5, 50, 5, 50, NA, NA, NA, NA, NA, 7, 25, 100, 30, 150,
        NA, NA, NA, NA, NA, NA, NA, 30, 5, 5, 10, 10, 15, 15, 15, 20,
        30, 5, 5, 5, NA, 7, 5, 10, 15, 10, 15, 25, 10, 15, 20, 5, 5,
        5, NA, 2000, 5, NA, NA, NA, NA, NA, NA, 2000, NA, NA, NA, 2000,
        NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,
        NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,
        NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,
        60, 60, 59, 59.9, 124, 124, 59, 59.9, NA, NA, NA, NA, NA, NA,
        NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,
        NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA)
   ,LEGALVALUES = c("|L|M|H",
        "|L|M|H", "|L|M|H", "|L|M|H", "|L|M|H", "|L|M|H", "|L|M|H", "|5|4|3|2|1",
        "|Absent|Rare|Common", "|None|Minor|Major", "|Forest|Agriculture|Range|Urban|Suburban/Town",
        "0-25|25-75|>75", "", "|L|M|H", "|L|M|H", "|L|M|H", "|L|M|H",
        "|L|M|H", "|L|M|H", "|L|M|H", "|L|M|H", "|L|M|H", "|L|M|H", "|L|M|H",
        "|L|M|H", "|L|M|H", "|L|M|H", "|L|M|H", "|L|M|H", "|5|4|3|2|1",
        "", "|L|M|H", "|L|M|H", "|L|M|H", "|L|M|H", "|L|M|H", "|L|M|H",
        "|L|M|H", "|L|M|H", "|L|M|H", "|L|M|H", "|L|M|H", "|L|M|H", "|L|M|H",
        "", "|P|GL|RI|RA|O|OT", "|C|F|M|L|O|OT", "", "|L|R", "|Y", "",
        "|C|F|M|L|O|OT", "|F|G|C|O|OT", "|P|GL|RI|RA|O|OT", "U|R|L|S|M|OG|OT|O",
        "", "|L|C|R", "|Y", "", "|F|G|C|O", "|P|GL|RI|RA", "", "|Y",
        "", "|F|G|C|O", "", "", "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "|Y", "", "|Y", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
        "", "", "", "|NOT MARKED|CENTER|LB|LC|RB|RC", "|Y", "", "|Y|N",
        "", "", "", "", "", "", "MID CHANNEL|OTHER|NOT MARKED", "", "|Y|N",
        "", "", "", "", "", "", "|WOODED|HERBACEOUS|BARREN|ARMORED|RIPRAP|OTHER|HERB",
        "", "", "|MACRO|LWD|OVERHANG|OTHER", "", "|< 0.5|> 0.6 to 2|> 2",
        "", "", "", "", "|NO FISH", "|Y", "", "", "", "|FINE|GRAVEL|COBBLE-BOULDER|OTHER",
        "", "", "", "", "", "", "", "", "", "", "|Y", "", "", "", "|Y",
        "|Y", "|Y", "|Y", "|Y", "|Y", "|Y", "|Y", "|Y", "|Y", "", "",
        "|Y", "|Y", "", "", "", "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "VELOCITY AREA|NBO|QVAL|TIMED FILLING",
        "", "", "", "", "", "", "", "", "|Y", "|Y", "|Y", "", "|Y", "|Y",
        "|X", "|X", "|Y", "|Y", "", "|Y", "|Deciduous|Coniferous|Broadleaf Evergreen",
        "|Y", "|Y", "|LOW|HIGH", "|DOMINANT|COMMON|SPARSE", "", "", "|NATURAL|SURROGATE",
        "", "", "", "", "", "", "|Y", "", "", "", "", "|Y", "", "", "",
        "", "|Y", "", "", "", "", "|Y", "", "", "", "", "|Y", "", "",
        "", "", "|Y", "", "", "", "", "|Y", "", "", "", "", "|Y", "",
        "", "", "|0|1|2|3|4", "", "|0|1|2|3|4", "|0|1|2|3|4", "|0|1|2|3|4",
        "|0|P|C|B", "|0|1|2|3|4", "|0|1|2|3|4", "|D|C|E|M|N", "|C|U|B|N",
        "", "|0|1|2|3|4", "|0|1|2|3|4", "|0|P|C|B", "|0|P|C|B", "|0|1|2|3|4",
        "|0|1|2|3|4", "|0|P|C|B", "|0|P|C|B", "|0|P|C|B", "|0|P|C|B",
        "|0|P|C|B", "|0|P|C|B", "|0|P|C|B", "|YES|NO", "", "|0|1|2|3|4",
        "|0|1|2|3|4", "", "|D|C|E|M|N", "|0|1|2|3|4", "|0|1|2|3|4", "|0|P|C|B",
        "|0|1|2|3|4", "", "", "", "", "", "", "|RS|RR|XB|SB|CB|GC|GF|SA|FN|HP|WD|OT",
        "|RS|RR|XB|SB|CB|GC|GF|SA|FN|HP|WD|OT", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "", "", "", "", "|RS|RR|XB|SB|CB|GC|GF|SA|FN|HP|WD|OT",
        "|RS|RR|XB|SB|CB|GC|GF|SA|FN|HP|WD|OT", "", "", "", "|JUDG|OBSV",
        "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "", "", "", "|0|1|2|3|4",
        "", "", "|0|1|2|3|4", "", "|0|1|2|3|4", "|0|1|2|3|4", "|0|P|C|B",
        "|0|1|2|3|4", "|0|1|2|3|4", "|D|C|E|M|N", "", "", "", "", "|0|1|2|3|4",
        "|0|1|2|3|4", "", "|0|P|C|B", "|0|P|C|B", "|0|1|2|3|4", "|0|1|2|3|4",
        "|0|P|C|B", "|0|1|2|3|4", "|0|P|C|B", "|0|P|C|B", "|0|P|C|B",
        "|0|P|C|B", "|0|P|C|B", "|0|P|C|B", "|RS|RR|RC|XB|SB|CB|GC|GF|SA|FN|HP|WD|OT",
        "|0|1|2|3|4", "|0|1|2|3|4", "", "|D|C|E|M|N", "|0|1|2|3|4", "|0|1|2|3|4",
        "|0|P|C|B", "", "|0|1|2|3|4", "", "|CON_VSHAPED|CON_BROAD|UNC_NARROW|UNC_BROAD",
        "|BEDROCK|HILLSLOPE|TERRACE|HUMAN|NOCONST", "|SINGLE|ANASTOM|BRAIDED",
        "", "", "|Y", "", "", "", "|TR|WT|LA|CL|NONE|Other|HL", "", "",
        "", "", "", "", "", "", "", "|Y|N", "NONE|Right|Left", "|Y|N",
        "", "|PP|PT|PL|PB|PD|P|GL|RI|RA|CA|FA|DR", "", "", "", "", "",
        "", "", "|N|W|R|B|F|BF|BR|BW|FB|FR|FW|FWR|NR|RB|RF|RW|RWB|RWF|WB|WBF|WBR|WF|WR|WRF",
        "|Y|N", "|Y|N", "|BH|BL|CB|GR|SA|FN|OT", "|Y|N", "", "", "",
        "", "", "", "", "", "", "", "", "", "", "|Y|N", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "|RS|RR|RC|XB|SB|CB|GC|GF|SA|FN|HP|WD|OT",
        "", "", "", "|Y", "", "|Y", "", "|Y", "", "", "", "|Y", "", "",
        "", "", "", "", "|NATURAL|SURROGATE", "|1", "|2", "|3", "|4",
        "|5", "|6", "|7", "|8", "|9", "|10", "|11", "|Y", "|Y", "|Y",
        "|Y", "|Y", "|Y", "|Y", "|Y", "|Y", "|Y", "|Y", "|Y", "", "|Y",
        "|Y", "|Y", "", "", "|Inaccessible|TEMP INACCESSIBLE|ACCESS DENIED|NACCESSIBLE|Access Denied",
        "|Dry - Visited|Dry - Not Visited|IMPOUNDED|OTHER|Wetland|Other|Impounded|Map Error|DRY-VISITED|DRY-NOT VISITED|MAP ERROR|WETLAND",
        "|NOT WADEABLE|Not Boatable|Not Wadable|OTHER|Not Wadeable|Other",
        "|No Samps", "|Wadeable|Boatable|Wadeable Interrupted|Partial Boatable|Partial Wadeable|Altered|BOATABLE",
        "|Y", "", "Y|N", "", "", "", "|WADEABLE|DRYVISIT|INACCPERM|BOATABLE|INTWADE|INACCTEMP|DRYNOVISIT|ACCDENIED|IMPOUNDED|OTHR_NSP|PARBYBOAT|NOTWADE|NOTBOAT|PARBYWADE|WETLAND|OTHR_NST|MAPERROR",
        "", "", "", "", "", "", "", "", "", "|SAMPLEABLE|NONSAMPPERM|NOACCESS|NONSAMPTEMP",
        "|Y", "", "", "|Y", "", "", "", "", "", "", "", "", "", "", "",
        "", "", "", "P|D|F", "PHAB_CHANB|PHAB_CHANBFRONT|PHAB_CHANW|BELG|BERW|PHAB_CHANCON|PHAB_THALW|PHAB_SLOPE|FLOW|CALI|FIELDMEAS|FISH|RIPLEG|INVA|ASSE|TORR|ASSE|PHAB_THAL|BELG|BERW|CHEM|ENTE|PAPA|PBIO|PCHL|PERI|FISHTV|SEDE|WCHL|PPCP|SNAG|WPFC|KICK",
        "", "", "LF|RT", "CT|LF|RT|LC|RC|NONE", "CD|CL|CR|CU|LF|RT|DN|UP|CT",
        "A|B|C|D|E|F|G|H|I|J|K|XA|XB|XC|XD|XE|XF|XG|XH|XI|XJ|XK|NOT MARKED",
        "", "|Y", NA, NA, "|Y|N", "|PO|GL|RI|RA|CA|FA|DR")
   )
  ,.Names = c("FORMABBR",
        "PARAMETER", "LABEL", "UNITS", "SAMPLE_TYPE", "RANGETYPE", "RANGELOW",
        "RANGEHIGH", "LEGALVALUES")
  ,row.names = c(NA, 635L)
  ,class = "data.frame"
  );
  return(rc)
}

# end of file