metsShorelineSubstrate <- function(df) {

################################################################################
# Function: metsShorelineSubstrate
# Title: Calculate NLA Shoreline Substrate Metrics
# Programmers: Curt Seeliger
#              Tom Kincaid
# Date: October 7, 2008
# Description:
#   This function calculates the shoreline substrate portion of the physical
#   habitat metrics for National Lakes Assessment (NLA) data.  The function
#   requires a data frame containing validated physical habitat data collected
#   using the NLA protocol.
# Function Revisions:
#   10/07/08 cws: quantile calculations using type 3 algorithm to mimic SAS 
#            results.
#   10/16/08 cws: changed to use normalizedCover() for all cover mets; was just
#            normalizing the diameter percentile mets using inline code.
#   10/17/08 cws: changed to use type 2 quantile calculation method, as this
#            actually matches SAS output using proc univariate.
#   10/21/08 cws: Correcting counts of missing parameters.  These are now zero.
#   02/27/09 cws: Calculation of ssiSiteVariety corrected.
#   03/08/13 cws: Copied from 2007 study and renamed.
#   12/06/13 cws: Added unit test based on 2007 data, RESULTs assumed to be
#            correct with the exception of NA counts, which in 2007 were set
#            to 0 later on (in nlaphab.r).  The metrics function was changed
#            to set those counts to integer 0 within the function and to 
#            return a long dataframe instead of a wide one.  The metrics
#            function was also changed to not return NA values for substrates
#            which were not recorded at a site (e.g. 7533 has no gravel, so
#            ssfcGravel, ssvGravel and ssfpGravel were NA but now are no longer
#            reported).  These NA values were an artifact of the 'wide'
#            organization of the output, and are commented out in the code
#            creating the expected values.
#   12/11/13 cws: Completed unit test with 2007 data. Corrected SAS results for
#            SSISITEVARIETY values for 7533, 7682 and 7961. Upcased metric
#            names.  Regression test using entire 2007 dataset shows the
#            following differences which are all expected:  SSISITEVARIETY is
#            changed from NA to the correct count in 19 sites (7518, 7533, 7534,
#            7598, 7682, 7724, 7760, 7791, 7818, 7862, 7895, 7926, 7956, 7961,
#            8069, 8101, 8797, 8845, 8846) which are the only sites with absent
#            substrate data.  Also SSN* counts at 57 sites which have no
#            shoreline substrate data are NA instead of 0.  Also the values of
#            SSOPCLASS and SSOFCLASS have all changed from NA to actual values.
#   06/12/14 tmk: Removed calls to the require() function.
# Arguments:
#   df = a data frame containing shoreline substrate data.  The data frame must
#     include columns that are named as follows:
#       UID - universal ID value, which uniquely identifies the site location, 
#             date of visit, visit order, habitat type, etc. for which metrics 
#             will be calculated.  For NLA, site ID, year and visit number are
#             used for this purpose.
#       STATION - the subordinate ID value, which identifies the location,
#               habitat type, order of occurence, etc. within a single UID.
#               For NLA, transect is used for this purpose.
#       PARAMETER - parameter name, which identifies the variables used in
#                   calculations. In wide data frame format, this argument
#                   would be used to name columns.  It is assumed that this
#                   argument has the following values: SS_BEDROCK, SS_BOULDERS, 
#                   SS_COBBLE, SS_GRAVEL, SS_SAND, SS_SILT, SS_ORGANIC,
#                   SS_OTHER, and SS_WOOD.
#       RESULT - parameter values, which are the values used in calculations.
#       UNITS - parameter units, which identifies the units in which the
#               parameter values are recorded.
# Output:
#   A data frame that contains the following columns:
#     UID - universal ID value
#     PARAMETER - metric name
#     RESULT - metric value
# Other Functions Required:
#   intermediateMessage - print messages generated by the metric calculation
#      functions
################################################################################

  # Print initial messages
  cat('Shoreline Substrate calculations:\n')
  intermediateMessage('Shoreline substrate mets', loc='start')

  ssData <- subset(df
                  ,PARAMETER %in% c('SS_BEDROCK', 'SS_BOULDERS', 'SS_COBBLE'
                                   ,'SS_GRAVEL', 'SS_SAND', 'SS_SILT'
                                   ,'SS_ORGANIC', 'SS_OTHER', 'SS_WOOD'
                                   )
                  )

  intermediateMessage('.1')

  # Set up recodings for presence, cover and characteristic diameter (both
  # actual and logged)
  presence04 <- data.frame(field=c(NA,'0','1','2','3','4')
                          ,calc=c(NA,0,1,1,1,1)
                          ,stringsAsFactors=FALSE
                          )

  cover04<-data.frame(field=c(NA,'0','1','2','3','4')
                     ,calc=c(NA,0,0.05,0.25,0.575,0.875)
                     ,stringsAsFactors=FALSE
                     )

  tt<-data.frame(class=c('SS_BEDROCK',       'SS_BOULDERS'
                        ,'SS_COBBLE',        'SS_GRAVEL'
                        ,'SS_SAND',          'SS_SILT'
                        ,'SS_ORGANIC',       'SS_WOOD',           'SS_OTHER'
                        )
                ,diam=c(gmean(c(4000,8000)), gmean(c(250,4000))
                       ,gmean(c(64,250)),    gmean(c(2,64))
                       ,gmean(c(0.06,2)),    gmean(c(0.001,0.06))
                       ,NA,                  NA,                  NA
                       )
                ,stringsAsFactors=FALSE
                       )
  diameters <- aggregate(list(lDiam = tt$diam)
                        ,list('class'=tt$class, 'diam'=tt$diam)
                        ,log10
                        )
  intermediateMessage('.2')

  
  # Calculate fractional presence of each substrate class
  ssPresence <- merge(ssData, presence04
                     ,by.x='RESULT', by.y='field'
                     ,all.x=TRUE)
  tt <- aggregate(list(RESULT = ssPresence$calc)
                 ,list('UID'=ssPresence$UID
                      ,'PARAMETER'=ssPresence$PARAMETER
                      ) 
                 ,mean, na.rm=TRUE
                 )
  meanPresence <- within(tt
				        ,PARAMETER <- ifelse(PARAMETER == 'SS_BEDROCK', 'SSFPBEDROCK'
									 ,ifelse(PARAMETER == 'SS_BOULDERS', 'SSFPBOULDERS'
									 ,ifelse(PARAMETER == 'SS_COBBLE', 'SSFPCOBBLE'
									 ,ifelse(PARAMETER == 'SS_GRAVEL', 'SSFPGRAVEL'
									 ,ifelse(PARAMETER == 'SS_SAND', 'SSFPSAND'
									 ,ifelse(PARAMETER == 'SS_SILT', 'SSFPSILT'
									 ,ifelse(PARAMETER == 'SS_ORGANIC', 'SSFPORGANIC'
									 ,ifelse(PARAMETER == 'SS_WOOD', 'SSFPWOOD'
									 ,ifelse(PARAMETER == 'SS_OTHER', 'SSFPOTHER', 'SSFPUNKNOWN'
									  )))))))))
					    )

  intermediateMessage('.3')


  # Calculate variety metrics: 
  #     ssiStaVariety = mean number of substrate classes at each station.
  #     ssiSiteVariety = total number of substrate classes present in site
  # The number of substrate classes at a station is the sum of their presences.
  # Note: SS_OTHER is not included in site variety index
  tt <- aggregate(list(sum=ssPresence$calc)
                 ,list('UID'=ssPresence$UID
                      ,'STATION'=ssPresence$STATION
                      )
                 ,sum, na.rm=TRUE
                 )
  ssiVariety <- aggregate(list(RESULT=tt$sum)
                            ,list('UID'=tt$UID)
                            ,mean, na.rm=TRUE
                            )
  ssiVariety$PARAMETER <- 'SSISTAVARIETY'

  tt <- subset(meanPresence, PARAMETER != 'SSFPOTHER')
  ssiSiteVariety <- aggregate(list(RESULT = tt$RESULT)
  							 ,list(UID=tt$UID)
					 		 ,function(x) {
								 sum(ifelse(x>0, 1, 0), na.rm=TRUE)		# sum up substrate presences
							  }
					  		 )
  ssiSiteVariety$PARAMETER <- 'SSISITEVARIETY'
  ssiVariety <- rbind(ssiVariety, ssiSiteVariety)

  intermediateMessage('.4')


  # Normalize covers of all shore substrate classes. 
  sscover <- merge(ssData, cover04, by.x='RESULT', by.y='field', all.x=TRUE)
  sscover <- normalizedCover(sscover, 'calc', 'normCover')
  
  # calculate mean cover of each substrate class
  tt <- aggregate(list(RESULT = sscover$normCover)
                 ,list('UID'=sscover$UID
                      ,'PARAMETER'=sscover$PARAMETER
                      ) 
                 ,mean, na.rm=TRUE
                 )
#
  meanCover <- within(tt
					 ,PARAMETER <- ifelse(PARAMETER == 'SS_BEDROCK', 'SSFCBEDROCK'
					 			  ,ifelse(PARAMETER == 'SS_BOULDERS', 'SSFCBOULDERS'
								  ,ifelse(PARAMETER == 'SS_COBBLE', 'SSFCCOBBLE'
								  ,ifelse(PARAMETER == 'SS_GRAVEL', 'SSFCGRAVEL'
								  ,ifelse(PARAMETER == 'SS_SAND', 'SSFCSAND'
								  ,ifelse(PARAMETER == 'SS_SILT', 'SSFCSILT'
								  ,ifelse(PARAMETER == 'SS_ORGANIC', 'SSFCORGANIC'
								  ,ifelse(PARAMETER == 'SS_WOOD', 'SSFCWOOD'
								  ,ifelse(PARAMETER == 'SS_OTHER', 'SSFCOTHER', 'SSFCUNKNOWN'
								   )))))))))
					 )

  intermediateMessage('.5')

  # calculate stdev cover of each substrate class
  tt <- aggregate(list(RESULT = sscover$normCover)
                 ,list('UID'=sscover$UID
                      ,'PARAMETER'=sscover$PARAMETER
                      ) 
                 ,sd, na.rm=TRUE
                 )
  sdCover <- within(tt
				   ,{PARAMETER <- ifelse(PARAMETER == 'SS_BEDROCK', 'SSVBEDROCK'
							   	 ,ifelse(PARAMETER == 'SS_BOULDERS', 'SSVBOULDERS'
								 ,ifelse(PARAMETER == 'SS_COBBLE', 'SSVCOBBLE'
								 ,ifelse(PARAMETER == 'SS_GRAVEL', 'SSVGRAVEL'
								 ,ifelse(PARAMETER == 'SS_SAND', 'SSVSAND'
								 ,ifelse(PARAMETER == 'SS_SILT', 'SSVSILT'
								 ,ifelse(PARAMETER == 'SS_ORGANIC', 'SSVORGANIC'
								 ,ifelse(PARAMETER == 'SS_WOOD', 'SSVWOOD'
								 ,ifelse(PARAMETER == 'SS_OTHER', 'SSVOTHER', 'SSVUNKNOWN'
								  )))))))))
					   
				    }
		   		   )

  intermediateMessage('.6')


  # count valid cover of each substrate class.  Fill in missing (NA) counts with 0, as was
  # done elsewhere in 2007.
  tt <- aggregate(list(RESULT = sscover$normCover)
                 ,list('UID'=sscover$UID
                      ,'PARAMETER'=sscover$PARAMETER
                      ) 
                 ,count
                 )
  tt <- within(expand.data.frame(tt, c('UID','PARAMETER'))
			  ,RESULT <- ifelse(is.na(RESULT), 0, RESULT)
			  )
  countSubstrates <- within(tt
						   ,{PARAMETER <- ifelse(PARAMETER == 'SS_BEDROCK', 'SSNBEDROCK'
										 ,ifelse(PARAMETER == 'SS_BOULDERS', 'SSNBOULDERS'
										 ,ifelse(PARAMETER == 'SS_COBBLE', 'SSNCOBBLE'
										 ,ifelse(PARAMETER == 'SS_GRAVEL', 'SSNGRAVEL'
										 ,ifelse(PARAMETER == 'SS_SAND', 'SSNSAND'
										 ,ifelse(PARAMETER == 'SS_SILT', 'SSNSILT'
										 ,ifelse(PARAMETER == 'SS_ORGANIC', 'SSNORGANIC'
										 ,ifelse(PARAMETER == 'SS_WOOD', 'SSNWOOD'
										 ,ifelse(PARAMETER == 'SS_OTHER', 'SSNOTHER', 'SSNUNKNOWN'
										  )))))))))
						    }
						   )
						   
						   
  intermediateMessage('.7')


  # Calculations using characteristic diameters of the substrate are based
  # on mean diameter*cover values at each transect.  Cover values are 
  # normalized prior to their use as weights for these means.
  #
  # Determine mean diameters, weighted by the normalized covers.  Note that
  # the normalization includes non-mineral substrates, but the following
  # calculations do not take them into account as they have no meaningful 
  # diameter.
  mineralCover <- subset(sscover
                        ,PARAMETER %in% c('SS_BEDROCK','SS_BOULDERS','SS_COBBLE'
                                         ,'SS_GRAVEL', 'SS_SAND', 'SS_SILT'
                                         )
                        ,select=names(sscover)[names(sscover) != 'normCover']
                  )
  mineralCover <- normalizedCover(mineralCover, 'calc', 'normCover')
  
  tt <- merge(mineralCover, diameters
             ,by.x='PARAMETER', by.y='class'
             ,all.x=TRUE
             )
  tt$wtLDiam <- tt$lDiam * tt$normCover

  diamSubstrate <- aggregate(list(meanLDiam = tt$wtLDiam)
                            ,list('UID'=tt$UID
                                 ,'STATION'=tt$STATION
                                 ) 
                            ,mean, na.rm=TRUE
                            )

  intermediateMessage('.8')


  # Estimate measures of diameter populations
  meanLDia <- aggregate(list(RESULT = diamSubstrate$meanLDiam)
                 ,list('UID'=diamSubstrate$UID)
                 ,mean, na.rm=TRUE
                 )
  meanLDia$PARAMETER <- 'SSXLDIA'

  sdLDia <- aggregate(list(RESULT = diamSubstrate$meanLDiam)
                 ,list('UID'=diamSubstrate$UID)
                 ,sd, na.rm=TRUE
                 )
  sdLDia$PARAMETER <- 'SSVLDIA'

  p16LDia <- aggregate(list(RESULT = diamSubstrate$meanLDiam)
                 ,list('UID'=diamSubstrate$UID)
                 ,quantile, 0.16, na.rm=TRUE, names=FALSE, type=2
                 )
  p16LDia$PARAMETER <- 'SS16LDIA'

  p25LDia <- aggregate(list(RESULT = diamSubstrate$meanLDiam)
                 ,list('UID'=diamSubstrate$UID)
                 ,quantile, 0.25, na.rm=TRUE, names=FALSE, type=2
                 )
  p25LDia$PARAMETER <- 'SS25LDIA'

  p50LDia <- aggregate(list(RESULT = diamSubstrate$meanLDiam)
                 ,list('UID'=diamSubstrate$UID)
                 ,quantile, 0.50, na.rm=TRUE, names=FALSE, type=2
                 )
  p50LDia$PARAMETER <- 'SS50LDIA'

  p75LDia <- aggregate(list(RESULT = diamSubstrate$meanLDiam)
                 ,list('UID'=diamSubstrate$UID)
                 ,quantile, 0.75, na.rm=TRUE, names=FALSE, type=2
                 )
  p75LDia$PARAMETER <- 'SS75LDIA'

  p84LDia <- aggregate(list(RESULT = diamSubstrate$meanLDiam)
                 ,list('UID'=diamSubstrate$UID)
                 ,quantile, 0.84, na.rm=TRUE, names=FALSE, type=2
                 )
  p84LDia$PARAMETER <- 'SS84LDIA'


  intermediateMessage('.9')


  # Determine most common substrate class by presence and by cover
  # (requires same site visits in meanPresence and meanCover in same order)
  #
  # Initialize these metrics with missing values, and add classes
  tt <- dcast(rbind(meanPresence,meanCover), UID~PARAMETER, value.var='RESULT')
  modeClasses <- subset(tt, select='UID')
  modeClasses$SSOPCLASS <- NA
  modeClasses$SSOFCLASS <- NA

  for(i in 1:nrow(tt)) {
      modeClasses$SSOPCLASS[i] <- modalClass(tt[i,]
                                            ,c('SSFPBEDROCK', 'SSFPBOULDERS'
                                              ,'SSFPCOBBLE',  'SSFPGRAVEL'
                                              ,'SSFPSAND',    'SSFPSILT'
                                              ,'SSFPORGANIC', 'SSFPWOOD'
                                              ,'SSFPOTHER'
                                              )
                                            ,c('Bedrock', 'Boulders'
                                              ,'Cobble',  'Gravel'
                                              ,'Sand',    'Silt'
                                              ,'Organic', 'Wood'
                                              ,'Other'
                                              )
                                            )
      modeClasses$SSOFCLASS[i] <- modalClass(tt[i,]
                                            ,c('SSFCBEDROCK', 'SSFCBOULDERS'
                                              ,'SSFCCOBBLE',  'SSFCGRAVEL'
                                              ,'SSFCSAND',    'SSFCSILT'
                                              ,'SSFCORGANIC', 'SSFCWOOD'
                                              ,'SSFCOTHER'
                                              )
                                            ,c('Bedrock', 'Boulders'
                                              ,'Cobble',  'Gravel'
                                              ,'Sand',    'Silt'
                                              ,'Organic', 'Wood'
                                              ,'Other'
                                              )
                                            )
  }

  modeClasses <- within(melt(modeClasses, 'UID'
						    ,variable.name='PARAMETER'
			                ,value.name='RESULT'
			                )
					   ,PARAMETER <- as.character(PARAMETER)
			   		   )
					   
  intermediateMessage('.10')


  # combine RESULTs into a dataframe
  ssMets <- rbind(meanPresence, meanCover, ssiVariety, sdCover, countSubstrates
				 ,meanLDia, sdLDia, p16LDia, p25LDia, p50LDia, p75LDia, p84LDia
				 ,modeClasses
				 )
  intermediateMessage(' Done.', loc='end')

  return(ssMets)

}



# end of file
