metsLittoralZone <- function(df, data2007=FALSE) {

################################################################################
# Function: metsLittoralZone
# Title: Calculate NLA Littoral Zone Metrics
# Programmers: Curt Seeliger
#              Tom Kincaid
# Date: October 14, 2008
# Description:
#   This function calculates the littoral zone portion of the physical
#   habitat metrics for National Lakes Assessment (NLA) data.  The function
#   requires a data frame containing validated physical habitat data collected
#   using the NLA protocol.
# Function Revisions:
#   10/14/08 cws: Started.
#   03/08/13 cws: Copied from 2007 study and renamed.
#   12/19/13 cws: Developed unit test using 2007 and 2012 data and refactored. 
#            Upcased column names and metric names; now returning long dataframe  
#            instead of wide.  Added LZFPALGAE, LZFPNONE, LZFPOILY, LZFPOTHER, 
#            LZFPSCUM calculations and removed LZIFILMVARIETY from results when 
#            using non-2007 data. Using modalValues() instead of modalvalue()
#            to allow reporting of ties in LZOFILM.  Regression tested results 
#            with entire 2007 data successfully, with the following expected 
#            differences: 177 rows in the 2007 results for 59 sites which do not 
#            have any SURFACE_FILM values recorded, and 3 different values each 
#            of LZFPFILM and LZIFILMVARIETY due to floating point truncation, 
#            and 18 different values of LZOFILM because those sites have 
#            multiple modal values.
#   01/30/14 cws: Removed commented out code.
#   06/12/14 tmk: Removed calls to the require() function.
# Arguments:
#   df = a data frame containing littoral zone data.  The data frame must
#     include columns that are named as follows:
#       UID - universal ID value, which uniquely identifies the site location, 
#             date of visit, visit order, habitat type, etc. for which metrics 
#             will be calculated.  For NLA, site ID, year and visit number are
#             used for this purpose.
#       STATION - the subordinate ID value, which identifies the location,
#               habitat type, order of occurence, etc. within a single UID.
#               For NLA, transect is used for this purpose.
#       PARAMETER - parameter name, which identifies the variables used in
#                   calculations. In wide data frame format, this argument
#                   would be used to name columns.  It is assumed that this
#                   argument has the following value: SURFACE_FILM.
#       RESULT - parameter values, which are the values used in calculations.
#   data2007 = a logical value, which equals TRUE if 2007 data is being
#     processed.  The default value is FALSE.
# Output:
#   A data frame that contains the following columns:
#     UID - universal ID value
#     PARAMETER - metric name
#     RESULT - metric value
# Other Functions Required:
#   intermediateMessage - print messages generated by the metric calculation
#      functions
################################################################################

  # Print initial messages
  cat('Littoral Zone calculations:\n')
  intermediateMessage('Littoral Zone mets', loc='start')

	lzData <- metsLittoralZone.prepareInput(df, data2007)
    intermediateMessage('.1')


    # Determine mode(s) of the surface film type
	modeFilm <- metsLittoralZone.modeFilm(lzData, data2007)
	intermediateMessage('.2')


    # Determine fractional presence of any type of film other than None
	presences <- metsLittoralZone.fractionalPresences(lzData, data2007)
    intermediateMessage('.3')


    # Determine mean number of any type of film other than None occuring
    # at a station
	variety <- metsLittoralZone.filmVariety(lzData, data2007)
    intermediateMessage('.4')


    # Assemble mets and send 'em back.
    lz <- rbind(modeFilm, presences, variety)
    intermediateMessage(' Done.', loc='end')

    return(lz)
}


metsLittoralZone.prepareInput <- function(df, data2007)
# Prepare Littoral zone data for subsequent calculations.
# Returns standardized dataframe with columns UID, PARAMETER, RESULT.
{
	lzData <- subset(df, PARAMETER=='SURFACE_FILM')

	if(data2007) {
		
		lzData <- within(lzData
			 	 		,RESULT <- ifelse(RESULT=='A', 'ALGAL_MAT'
								  ,ifelse(RESULT=='N', 'NONE'
								  ,ifelse(RESULT=='',  'NONE'					  
								  ,ifelse(RESULT=='O', 'OTHER'
								  ,ifelse(RESULT=='P', 'OILY'
								  ,ifelse(RESULT=='S', 'SCUM', 'UNKNOWN'
						    	   ))))))
						)
						
	} else {
		
		lzData$RESULT <- with(lzData, ifelse(grepl('^OTHER.+$', RESULT), 'OTHER', RESULT))
		
	}

	return(lzData)
}


metsLittoralZone.modeFilm <- function(df, data2007)
# Determine most common film type.  Returns dataframe with
# columns UID, PARAMETER, RESULT
{
	modeFilm <- aggregate(list(RESULT=df$RESULT)
						 ,list(UID=df$UID)
						 ,modalValues, na.rm=TRUE
						 )
	modeFilm$PARAMETER <- 'LZOFILM'
	modeFilm$RESULT <- as.character(modeFilm$RESULT)	# modalvalue() returns factor, darn it.
	
	if(data2007) {
#		modeFilm$RESULT <- with(modeFilm
#							   , ifelse(RESULT=='ALGAL_MAT', 'A'
#								,ifelse(RESULT=='NONE', 	 'N'
#								,ifelse(RESULT=='OTHER', 	 'O'
#								,ifelse(RESULT=='OILY', 	 'P'
#								,ifelse(RESULT=='SCUM', 	 'S', 'UNKNOWN'
#								 )))))
#							   )
		modeFilm$RESULT <- with(modeFilm
						       , gsub('ALGAL_MAT',	'A'
							    ,gsub('NONE', 	 	'N'
							    ,gsub('OTHER', 	 	'O'
							    ,gsub('OILY', 	 	'P'
							    ,gsub('SCUM', 	 	'S', RESULT
												)))))
							  )
	}
	
	return(modeFilm)
}


metsLittoralZone.fractionalPresences <- function(df, data2007)
# Determines fractional presences of film types, including 'any' film other 
# than NONE. Returns dataframe with columns UID, PARAMETER, RESULT.
{
	df$any <- with(df, ifelse(RESULT=='NONE', 0, 1))
	fpAny <- aggregate(list(RESULT=df$any)
					  ,list(UID=df$UID)
					  ,protectedMean, na.rm=TRUE
					  )
	fpAny$PARAMETER <- 'LZFPFILM'
	
	
	if(data2007) {
		fpIndivs <- NULL
	} else {
		
		tt <- aggregate(list(RESULT = df$RESULT=='ALGAL_MAT')
				,list(UID=df$UID)
				,protectedMean, na.rm=TRUE
		)
		fpAlgae <- within(tt, PARAMETER <- 'LZFPALGAE')
		
		tt <- aggregate(list(RESULT = df$RESULT=='NONE')
				,list(UID=df$UID)
				,protectedMean, na.rm=TRUE
		)
		fpNone <- within(tt, PARAMETER <- 'LZFPNONE')
		
		tt <- aggregate(list(RESULT = df$RESULT=='OILY')
				,list(UID=df$UID)
				,protectedMean, na.rm=TRUE
		)
		fpOily <- within(tt, PARAMETER <- 'LZFPOILY')
		
		tt <- aggregate(list(RESULT = df$RESULT=='OTHER')
				,list(UID=df$UID)
				,protectedMean, na.rm=TRUE
		)
		fpOther <- within(tt, PARAMETER <- 'LZFPOTHER')
		
		tt <- aggregate(list(RESULT = df$RESULT=='SCUM')
				,list(UID=df$UID)
				,protectedMean, na.rm=TRUE
		)
		fpScum <- within(tt, PARAMETER <- 'LZFPSCUM')
		
		fpIndivs <- rbind(fpAlgae, fpNone, fpOily, fpOther, fpScum)
		
	}
	
	rc <- rbind(fpAny, fpIndivs)
	
	return(rc)
}


metsLittoralZone.filmVariety <- function(df, data2007)
# Determines variety of film types, including 'any' film other 
# than NONE. Returns dataframe with columns UID, PARAMETER, RESULT.
#
# NOTE: This metric is deprecated from post-2007 calculations as it 
# is neither well defined nor calculated correctly. 
{
	if(data2007) {
		
		df$any <- with(df, ifelse(RESULT=='NONE', 0, 1))
		tt <- aggregate(df$any
					   ,list(UID=df$UID, STATION=df$STATION)
					   ,sum, na.rm=TRUE
					   )
		variety <- aggregate(list(RESULT=tt$x)
							,list(UID=tt$UID)
							,mean, na.rm=TRUE
							)
		variety$PARAMETER <- 'LZIFILMVARIETY'

	} else {
		
		variety <- NULL	# metric is deprecated
		
	}
	
	return(variety)	
}



# end of file
