nrsaRiparianVegetation <- function(canopyCoverLargeDiameter = NULL
                                  ,canopyCoverSmallDiameter = NULL
                                  ,canopyVegetationType = NULL
                                  ,groundCoverBare = NULL
                                  ,groundCoverNonwoody = NULL
                                  ,groundCoverWoody = NULL
                                  ,understoryCoverNonwoody = NULL
                                  ,understoryCoverWoody = NULL
                                  ,understoryVegetationType = NULL
                                  ,coverCalculationValues = data.frame(field=c(NA,'0','1','2','3','4')
                                                                      ,calc=c(NA,0,0.05,0.25,0.575,0.875)
                                                                      ,stringsAsFactors=FALSE
                                                                      )
                                  ) {

################################################################################
# Function: metsRiparianVegetation
# Title: Calculate NRSA Riparian Vegetation Metrics
# Programmers: Curt Seeliger
#              Tom Kincaid
# Date: February 17, 2010
# Description:
#   This function calculates the riparian vegetation portion of the physical
#   habitat metrics for National Rivers and Streams Assessment (NRSA) data.  The
#   function requires a data frame containing the visible riparian damage data
#   file.
# Function Revisions:
#   02/17/10 cws: Created.
#   03/22/10 cws: Added missing call to checkEquals.
#   03/25/10 cws: Changed diff() calls to dfCompare(), nlaLengthen() to
#            dfLengthen().
#   03/31/10 cws: Added on.exit() call.
#   09/16/10 cws: Removed hardcoding of NRSA database name, using NRSAdbName
#            instead.
#   07/31/12 tmk: Removed calls to the require() function.  Removed use of ODBC
#            data connection and replaced with data input from csv files using a
#            call to function read.csv.  Added argument tbl to the function to
#            identify name of the data file.  Added argument NRSAdir to the
#            function to identify the directory from which the data file is read
#            and to which the output metrics file is written.
#   12/21/12 tmk: Modified data input to use a data frame containing the data
#            file rather than a csv file.  Modified output to be a data frame
#            rather than a csv file.  Removed RUnit functions.
#   01/11/13 tmk: Inserted code to convert factors in the input data frame to
#            character variables.
# Arguments:
#   visrip = a data frame containing the visible riparian damage data file.  The
#     data frame must include columns that are named as follows:
#       UID - universal ID value
#       SAMPLE_TYPE - sample type
#       TRANSECT - transect label
#       TRANSDIR - transverse location along transect
#       PARAMETER - identifier for each measurement, assessment, score, etc.
#       RESULT - measurement associated with PARAMETER column
#       FLAG - flag
#   Note that possible values for variables in the input data frame are
#   provided in the document named "NRSA Documentation.pdf" included in the help
#   directory for the package.
# Output:
#   Either a data frame when metric calculation is successful or a character
#   string containing an error message when metric calculation is not
#   successful.  The data frame contains the following columns:
#     UID - universal ID value
#     METRIC - metric name
#     RESULT - metric value
# Other Functions Required:
#   intermediateMessage - print messages generated by the metric calculation
#      functions
#   metsRiparianVegetation.1 - calculate metrics
################################################################################

# # Print an initial message
#   cat('Riparian Vegetation calculations:\n')
# 
# # Convert factors to character variables in the visrip data frame
#   intermediateMessage('.1 Convert factors to character variables.', loc='end')
#   visrip <- convert_to_char(visrip)
# 
# # Subset the visrip data frame to retain desired values in the column named
# # PARAMETER
#   intermediateMessage('.2 Subset the data frame.', loc='end')
#   df <- subset(visrip ,PARAMETER %in% c('CANBTRE', 'CANSTRE', 'CANVEG',
#     'UNDWDY', 'UNDNWDY', 'UNDERVEG','GCWDY', 'GCNWDY', 'BARE'))
# 
# # Calculate the metrics
#   intermediateMessage('.3 Call function metsRiparianVegetation.1.', loc='end')
#   mets <- metsRiparianVegetation.1(df)
#   row.names(mets) <- 1:nrow(mets)
# 
# # Print an exit message
#   intermediateMessage('Done.', loc='end')
# 
# # Return results
#   return(mets)
# }
# 
# 
# 
# metsRiparianVegetation.1 <- function(visrip) {
# 
# # Calculates visible riparian vegetation metrics.
# # Returns a dataframe of the metrics upon completion, or a character string
# # describing the problem if one occurs.
# #
# # ARGUMENTS:
# # visrip    dataframe with visible riparian vegetation data
# #

    intermediateMessage('Starting riparian vegetation metrics', loc='start')
    absentAsNULL <- function(df, ifdf, ...) {
        if(is.null(df)) return(NULL)
        else if(!is.data.frame(df)) return(NULL)
        else if(nrow(df) == 0) return (NULL)
        else if(is.function(ifdf)) return(ifdf(df, ...))
        else return(df)
    }
    ifdf <- function(df, ...) {
        if(is.null(...)) return(NULL)
        else if(all(is.na(...))) return(NULL)

        args <- list(...)
        pName <- args[[1]]
        rc <- df %>% 
              select(SITE, TRANSECT, BANK, VALUE) %>% 
              mutate(PARAMETER=pName)
        return(rc)
    }

    # Recreate old argument from new ones for now, rip out guts later
    visrip <- rbind(absentAsNULL(canopyCoverLargeDiameter, ifdf, 'CANBTRE')
                   ,absentAsNULL(canopyCoverSmallDiameter, ifdf, 'CANSTRE')
                   ,absentAsNULL(canopyVegetationType, ifdf, 'CANVEG')
                   ,absentAsNULL(groundCoverBare, ifdf, 'BARE')
                   ,absentAsNULL(groundCoverNonwoody, ifdf, 'GCNWDY')
                   ,absentAsNULL(groundCoverWoody, ifdf, 'GCWDY')
                   ,absentAsNULL(understoryCoverNonwoody, ifdf, 'UNDNWDY')
                   ,absentAsNULL(understoryCoverWoody, ifdf, 'UNDWDY')
                   ,absentAsNULL(understoryVegetationType, ifdf, 'UNDERVEG')
                   )
    if(is.null(visrip)) return(NULL)

  # Canopy type fractions
  tt <- subset(visrip, PARAMETER=='CANVEG')
  pcan_c <- aggregate(list('VALUE' = tt$VALUE)
                     ,list('SITE' = tt$SITE)
                     ,function(x) { mean(x=='C', na.rm=TRUE) }
                     )
  pcan_c$METRIC<-'pcan_c'
  pcan_d <- aggregate(list('VALUE' = tt$VALUE)
                     ,list('SITE' = tt$SITE)
                     ,function(x) { mean(x=='D', na.rm=TRUE) }
                     )
  pcan_d$METRIC<-'pcan_d'
  pcan_e <- aggregate(list('VALUE' = tt$VALUE)
                     ,list('SITE' = tt$SITE)
                     ,function(x) { mean(x=='E', na.rm=TRUE) }
                     )
  pcan_e$METRIC<-'pcan_e'
  pcan_m <- aggregate(list('VALUE' = tt$VALUE)
                     ,list('SITE' = tt$SITE)
                     ,function(x) { mean(x=='M', na.rm=TRUE) }
                     )
  pcan_m$METRIC<-'pcan_m'
  pcan_n <- aggregate(list('VALUE' = tt$VALUE)
                     ,list('SITE' = tt$SITE)
                     ,function(x) { mean(x=='N', na.rm=TRUE) }
                     )
  pcan_n$METRIC<-'pcan_n'

  canopyTypes <- rbind(pcan_c, pcan_d, pcan_e, pcan_m, pcan_n)
  intermediateMessage('.1')
  
  # Mid-layer type fractions
  tt <- subset(visrip, PARAMETER=='UNDERVEG')
  pmid_c <- aggregate(list('VALUE' = tt$VALUE)
                     ,list('SITE' = tt$SITE)
                     ,function(x) { mean(x=='C', na.rm=TRUE) }
                     )
  pmid_c$METRIC<-'pmid_c'
  pmid_d <- aggregate(list('VALUE' = tt$VALUE)
                     ,list('SITE' = tt$SITE)
                     ,function(x) { mean(x=='D', na.rm=TRUE) }
                     )
  pmid_d$METRIC<-'pmid_d'
  pmid_e <- aggregate(list('VALUE' = tt$VALUE)
                     ,list('SITE' = tt$SITE)
                     ,function(x) { mean(x=='E', na.rm=TRUE) }
                     )
  pmid_e$METRIC<-'pmid_e'
  pmid_m <- aggregate(list('VALUE' = tt$VALUE)
                     ,list('SITE' = tt$SITE)
                     ,function(x) { mean(x=='M', na.rm=TRUE) }
                     )
  pmid_m$METRIC<-'pmid_m'
  pmid_n <- aggregate(list('VALUE' = tt$VALUE)
                     ,list('SITE' = tt$SITE)
                     ,function(x) { mean(x=='N', na.rm=TRUE) }
                     )
  pmid_n$METRIC<-'pmid_n'

  midlayerTypes <- rbind(pmid_c, pmid_d, pmid_e, pmid_m, pmid_n)
  intermediateMessage('.2')


  # Vegetation class area cover characterizations -- individual classes
  # Use arithmetic means of end points to numerically characterize each cover
  # class.
  cover04 <- coverCalculationValues
            
  tt <- merge(subset(visrip, PARAMETER=='CANBTRE')
            ,cover04
            ,by.x='VALUE', by.y='field'
            ,all.x=TRUE
            )
  xcl <- aggregate(list('VALUE'=tt$calc)
                  ,list('SITE'=tt$SITE)
                  ,mean, na.rm=TRUE
                  )
  xcl$METRIC <- 'xcl'

  tt <- merge(subset(visrip, PARAMETER=='CANSTRE')
            ,cover04
            ,by.x='VALUE', by.y='field'
            ,all.x=TRUE
            )
  xcs <- aggregate(list('VALUE'=tt$calc)
                  ,list('SITE'=tt$SITE)
                  ,mean, na.rm=TRUE
                  )
  xcs$METRIC <- 'xcs'

  tt <- merge(subset(visrip, PARAMETER=='UNDWDY')
            ,cover04
            ,by.x='VALUE', by.y='field'
            ,all.x=TRUE
            )
  xmw <- aggregate(list('VALUE'=tt$calc)
                  ,list('SITE'=tt$SITE)
                  ,mean, na.rm=TRUE
                  )
  xmw$METRIC <- 'xmw'

  tt <- merge(subset(visrip, PARAMETER=='UNDNWDY')
            ,cover04
            ,by.x='VALUE', by.y='field'
            ,all.x=TRUE
            )
  xmh <- aggregate(list('VALUE'=tt$calc)
                  ,list('SITE'=tt$SITE)
                  ,mean, na.rm=TRUE
                  )
  xmh$METRIC <- 'xmh'

  tt <- merge(subset(visrip, PARAMETER=='GCWDY')
            ,cover04
            ,by.x='VALUE', by.y='field'
            ,all.x=TRUE
            )
  xgw <- aggregate(list('VALUE'=tt$calc)
                  ,list('SITE'=tt$SITE)
                  ,mean, na.rm=TRUE
                  )
  xgw$METRIC <- 'xgw'

  tt <- merge(subset(visrip, PARAMETER=='GCNWDY')
            ,cover04
            ,by.x='VALUE', by.y='field'
            ,all.x=TRUE
            )
  xgh <- aggregate(list('VALUE'=tt$calc)
                  ,list('SITE'=tt$SITE)
                  ,mean, na.rm=TRUE
                  )
  xgh$METRIC <- 'xgh'

  tt <- merge(subset(visrip, PARAMETER=='BARE')
            ,cover04
            ,by.x='VALUE', by.y='field'
            ,all.x=TRUE
            )
  xgb <- aggregate(list('VALUE'=tt$calc)
                  ,list('SITE'=tt$SITE)
                  ,mean, na.rm=TRUE
                  )
  xgb$METRIC <- 'xgb'
  
  individualCovers <- rbind(xcl, xcs, xmw, xmh, xgw, xgh, xgb)
  intermediateMessage('.3')

  
  # Vegetation class area cover characterizations -- combinations of classes
  tt <- merge(subset(visrip, PARAMETER %in% c('CANBTRE','CANSTRE'))
             ,cover04
             ,by.x='VALUE', by.y='field'
             ,all.x=TRUE
             )

  ss <- aggregate(tt$calc
                 ,list('SITE'=tt$SITE, 'TRANSECT'=tt$TRANSECT, 'BANK'=tt$BANK)
                 ,function(x) {if(all(is.na(x))) { NA } else {sum(x, na.rm=TRUE) } }
                 )
  xc <- aggregate(list('VALUE'=ss$x)
                 ,list('SITE'=ss$SITE)
                 ,mean, na.rm=TRUE
                 )
  xc$METRIC <- 'xc'
  intermediateMessage('.4')

  tt <- merge(subset(visrip, PARAMETER %in% c('UNDWDY','UNDNWDY'))
             ,cover04
             ,by.x='VALUE', by.y='field'
             ,all.x=TRUE
             )
  ss <- aggregate(tt$calc
                 ,list('SITE'=tt$SITE, 'TRANSECT'=tt$TRANSECT, 'BANK'=tt$BANK)
                 ,function(x) {if(all(is.na(x))) { NA } else {sum(x, na.rm=TRUE) } }
                 )
  xm <- aggregate(list('VALUE'=ss$x)
                 ,list('SITE'=ss$SITE)
                 ,mean, na.rm=TRUE
                 )
  xm$METRIC <- 'xm'
  intermediateMessage('.5')

  tt <- merge(subset(visrip, PARAMETER %in% c('CANBTRE','CANSTRE','UNDWDY'))
             ,cover04
             ,by.x='VALUE', by.y='field'
             ,all.x=TRUE
             )
  ss <- aggregate(tt$calc
                 ,list('SITE'=tt$SITE, 'TRANSECT'=tt$TRANSECT, 'BANK'=tt$BANK)
                 ,function(x) {if(all(is.na(x))) { NA } else {sum(x, na.rm=TRUE) } }
                 )
  xcmw <- aggregate(list('VALUE'=ss$x)
                 ,list('SITE'=ss$SITE)
                 ,mean, na.rm=TRUE
                 )
  xcmw$METRIC <- 'xcmw'
  intermediateMessage('.6')

  tt <- merge(subset(visrip, PARAMETER %in% c('CANBTRE','CANSTRE','UNDWDY','UNDNWDY'))
             ,cover04
             ,by.x='VALUE', by.y='field'
             ,all.x=TRUE
             )
  ss <- aggregate(tt$calc
                 ,list('SITE'=tt$SITE, 'TRANSECT'=tt$TRANSECT, 'BANK'=tt$BANK)
                 ,function(x) {if(all(is.na(x))) { NA } else {sum(x, na.rm=TRUE) } }
                 )
  xcm <- aggregate(list('VALUE'=ss$x)
                 ,list('SITE'=ss$SITE)
                 ,mean, na.rm=TRUE
                 )
  xcm$METRIC <- 'xcm'
  intermediateMessage('.7')

  tt <- merge(subset(visrip, PARAMETER %in% c('GCWDY','GCNWDY'))
             ,cover04
             ,by.x='VALUE', by.y='field'
             ,all.x=TRUE
             )
  ss <- aggregate(tt$calc
                 ,list('SITE'=tt$SITE, 'TRANSECT'=tt$TRANSECT, 'BANK'=tt$BANK)
                 ,function(x) {if(all(is.na(x))) { NA } else {sum(x, na.rm=TRUE) } }
                 )
  xg <- aggregate(list('VALUE'=ss$x)
                 ,list('SITE'=ss$SITE)
                 ,mean, na.rm=TRUE
                 )
  xg$METRIC <- 'xg'
  intermediateMessage('.8')

  tt <- merge(subset(visrip, PARAMETER %in% c('CANBTRE','CANSTRE','UNDWDY','GCWDY'))
             ,cover04
             ,by.x='VALUE', by.y='field'
             ,all.x=TRUE
             )
  ss <- aggregate(tt$calc
                 ,list('SITE'=tt$SITE, 'TRANSECT'=tt$TRANSECT, 'BANK'=tt$BANK)
                 ,function(x) {if(all(is.na(x))) { NA } else {sum(x, na.rm=TRUE) } }
                 )
  xcmgw <- aggregate(list('VALUE'=ss$x)
                 ,list('SITE'=ss$SITE)
                 ,mean, na.rm=TRUE
                 )
  xcmgw$METRIC <- 'xcmgw'
  intermediateMessage('.9')


  tt <- merge(subset(visrip, PARAMETER %in% c('CANBTRE','CANSTRE'
                                             ,'UNDWDY','UNDNWDY'
                                             ,'GCWDY','GCNWDY'
                                             )
                    )
             ,cover04
             ,by.x='VALUE', by.y='field'
             ,all.x=TRUE
             )
  ss <- aggregate(tt$calc
                 ,list('SITE'=tt$SITE, 'TRANSECT'=tt$TRANSECT, 'BANK'=tt$BANK)
                 ,function(x) {if(all(is.na(x))) { NA } else {sum(x, na.rm=TRUE) } }
                 )
  xcmg <- aggregate(list('VALUE'=ss$x)
                 ,list('SITE'=ss$SITE)
                 ,mean, na.rm=TRUE
                 )
  xcmg$METRIC <- 'xcmg'
  intermediateMessage('.10')

  combinedCovers <- rbind(xc, xm, xcmw, xcm, xg, xcmgw, xcmg)
  intermediateMessage('.11')

  
  # Vegetation class presence characterizations
  visrip$presence <- ifelse(is.na(visrip$VALUE), NA
                    ,ifelse(visrip$VALUE=='0', FALSE, TRUE
                     ))

  tt <- subset(visrip, PARAMETER %in% c('CANBTRE','CANSTRE'))
  ss <- aggregate(tt$presence
                 ,list('SITE'=tt$SITE, 'TRANSECT'=tt$TRANSECT, 'BANK'=tt$BANK)
                 ,any
                 )
  xpcan <- aggregate(list('VALUE'=ss$x)
                    ,list('SITE'=ss$SITE)
                    ,mean, na.rm=TRUE
                    )
  xpcan$METRIC <- 'xpcan'

  tt <- subset(visrip, PARAMETER %in% c('UNDWDY','UNDNWDY'))
  ss <- aggregate(tt$presence
                 ,list('SITE'=tt$SITE, 'TRANSECT'=tt$TRANSECT, 'BANK'=tt$BANK)
                 ,any
                 )
  xpmid <- aggregate(list('VALUE'=ss$x)
                    ,list('SITE'=ss$SITE)
                    ,mean, na.rm=TRUE
                    )
  xpmid$METRIC <- 'xpmid'

  tt <- subset(visrip, PARAMETER %in% c('GCWDY','GCNWDY'))
  ss <- aggregate(tt$presence
                 ,list('SITE'=tt$SITE, 'TRANSECT'=tt$TRANSECT, 'BANK'=tt$BANK)
                 ,any
                 )
  xpgveg <- aggregate(list('VALUE'=ss$x)
                    ,list('SITE'=ss$SITE)
                    ,mean, na.rm=TRUE
                    )
  xpgveg$METRIC <- 'xpgveg'

  tt <- subset(visrip, PARAMETER %in% c('UNDWDY','GCWDY'))
  ss <- aggregate(tt$presence
                 ,list('SITE'=tt$SITE, 'TRANSECT'=tt$TRANSECT, 'BANK'=tt$BANK)
                 ,function(x) {if(all(is.na(x))) { NA } else {all(x, na.rm=TRUE) } }
                 )
  xpmgw <- aggregate(list('VALUE'=ss$x)
                    ,list('SITE'=ss$SITE)
                    ,mean, na.rm=TRUE
                    )
  xpmgw$METRIC <- 'xpmgw'

  tt <- subset(visrip, PARAMETER %in% c('CANBTRE','CANSTRE'))
  cc <- aggregate(list('can'=tt$presence)
                 ,list('SITE'=tt$SITE, 'TRANSECT'=tt$TRANSECT, 'BANK'=tt$BANK)
                 ,any
                 )
  tt <- subset(visrip, PARAMETER %in% c('UNDWDY','UNDNWDY'))
  uu <- aggregate(list('und'=tt$presence)
                 ,list('SITE'=tt$SITE, 'TRANSECT'=tt$TRANSECT, 'BANK'=tt$BANK)
                 ,any
                 )
  ss <- merge(cc, uu, by=c('SITE','TRANSECT','BANK'), all=TRUE)
  ss$both <- ss$can & ss$und
  xpcm <- aggregate(list('VALUE'=ss$both)
                    ,list('SITE'=ss$SITE)
                    ,mean, na.rm=TRUE
                    )
  xpcm$METRIC <- 'xpcm'

  tt <- subset(visrip, PARAMETER %in% c('UNDWDY','UNDNWDY'))
  uu <- aggregate(list('und'=tt$presence)
                 ,list('SITE'=tt$SITE, 'TRANSECT'=tt$TRANSECT, 'BANK'=tt$BANK)
                 ,any
                 )
  tt <- subset(visrip, PARAMETER %in% c('GCWDY','GCNWDY'))
  gg <- aggregate(list('gnd'=tt$presence)
                 ,list('SITE'=tt$SITE, 'TRANSECT'=tt$TRANSECT, 'BANK'=tt$BANK)
                 ,any
                 )
  ss <- merge(uu, gg, by=c('SITE','TRANSECT','BANK'), all=TRUE)
  ss$both <- ss$und & ss$gnd
  xpmg <- aggregate(list('VALUE'=ss$both)
                    ,list('SITE'=ss$SITE)
                    ,mean, na.rm=TRUE
                    )
  xpmg$METRIC <- 'xpmg'

  tt <- subset(visrip, PARAMETER %in% c('CANBTRE','CANSTRE'))
  cc <- aggregate(list('can'=tt$presence)
                 ,list('SITE'=tt$SITE, 'TRANSECT'=tt$TRANSECT, 'BANK'=tt$BANK)
                 ,any
                 )
  tt <- subset(visrip, PARAMETER %in% c('UNDWDY','UNDNWDY'))
  uu <- aggregate(list('und'=tt$presence)
                 ,list('SITE'=tt$SITE, 'TRANSECT'=tt$TRANSECT, 'BANK'=tt$BANK)
                 ,any
                 )
  tt <- subset(visrip, PARAMETER %in% c('GCWDY','GCNWDY'))
  gg <- aggregate(list('gnd'=tt$presence)
                 ,list('SITE'=tt$SITE, 'TRANSECT'=tt$TRANSECT, 'BANK'=tt$BANK)
                 ,any
                 )
  ss <- merge(cc, uu, by=c('SITE','TRANSECT','BANK'), all=TRUE)
  ss <- merge(ss, gg, by=c('SITE','TRANSECT','BANK'), all=TRUE)
  ss$all3 <- ss$can & ss$und & ss$gnd
  xpcmg <- aggregate(list('VALUE'=ss$all3)
                    ,list('SITE'=ss$SITE)
                    ,mean, na.rm=TRUE
                    )
  xpcmg$METRIC <- 'xpcmg'

  presences <- rbind(xpcan, xpmid, xpgveg, xpmgw, xpcm, xpmg, xpcmg)
  intermediateMessage('.5')

                           
  # Combine groups of metrics and convert NaN calculations to NA
  mets <- rbind(canopyTypes, midlayerTypes, individualCovers, combinedCovers
               ,presences
               )
  mets$VALUE <- as.character(ifelse(is.nan(as.numeric(mets$VALUE)), NA, mets$VALUE))
  intermediateMessage('.  Done.', loc='end')

  return(mets)
}



# end of file
